### ISSUE TITLE
Error - Library not found ~|FBSDKCorekit

### ISSUE THREAD

**Issue by kamalkam** [facebook/facebook-ios-sdk#1160]
## Checklist

I ve installed All the pods "FBSDKShare kit - FBSDKLogin kit- FBSDKCorekit
 I ve installed the facebook sdk into my project and installed all the pods and when i open xcode project it show 
Library not found ~|FBSDKCorekit
- Xcode Version: `11.2.1'

## Goals
 I want to build my project so i can upload it to the appstore 

## Actual Results

Error showing when i try to build even if i ve download the FBSDKCorekit manullay and add it to my project on the framework folder the error keeps showing

**Comment by tianqibt** [comment]
Would you please provide the version of FBSDK you are using? Also it would be helpful if you can paste the screenshot of your podfile. Thanks!

**Comment by kamalkam** [comment]
I m using FBSDK 5.6.0 
And xcode 11.2.1
Here are somescreenshots
![IMG-20191224-WA0002](https://user-images.githubusercontent.com/58614922/71419036-c9f83880-266d-11ea-91af-8069bd42a447.jpg)
![IMG-20191224-WA0003](https://user-images.githubusercontent.com/58614922/71419051-d8deeb00-266d-11ea-9839-7ddfc523988f.jpg)

**Comment by kamalkam** [comment]
I ve run a command on terminal to install the Facebook kits "FBSDKSharekit,FBSDKLoginkit,FBSDKCorekit
Here is the command that i used 
Pod install --verbose

**Comment by tianqibt** [comment]
Please use our latest version 5.13.0, and let us know if the issue still exist.

**Comment by kamalkam** [comment]
What i did is i run this command on terminal "pod install --verbose""
And when i click enter it install the FBSDKSharekit .FBSDKCorekit,FBSDKLoginkit  version 5.3.0 automaticly .. Also i try to download the FBSDKCoreKit library separitly and when i add it to framework folder same issue keeps showing

**Comment by ZebingZong** [comment]
@kamalkam You will need to update the Podfile manually to point the target version to 5.13.0, here is more guides regarding the podfile (https://guides.cocoapods.org/syntax/podfile.html). Please let us know if you have further questions. Thanks!

**Comment by kamalkam** [comment]
I m not sure what i need to do .. Do i need to update the facebook sdk from the terminal by following this solution https://guides.cocoapods.org/syntax/podfile.html  or do i need to modifie the podfile from my project

**Comment by ZebingZong** [comment]
You just need to change the pod file in your own project.

**Comment by ZebingZong** [comment]
@kamalkam I will close it for now. Feel free to reopen it if you still have the issue. Thank!

**Comment by kamalkmll** [comment]
here is what i did 
i opened the pod file "text edit" and i ve added 
this Line 
pod 'AFNetworking', '~> 1.0'

![Screen Shot 2019-12-28 at 02 57 04](https://user-images.githubusercontent.com/59124373/71537559-4749d480-291e-11ea-9321-902794c7d865.png)
Thank You For Your help

**Comment by kamalkmll** [comment]
and When i try to build on xcode again same error showning 
library not found for -lFBSDKCoreKit

**Comment by kamalkmll** [comment]
![Screen Shot 2019-12-28 at 03 41 09](https://user-images.githubusercontent.com/59124373/71537964-fb019300-2923-11ea-82d8-2fc61219f7ba.png)
here is the library that i ve downloaded 
i m not sure where is the probleme 
is it from the library version or xcode can't detect path to the library

**Comment by kamalkam** [comment]
![Screen Shot 2019-12-28 at 03 46 29](https://user-images.githubusercontent.com/58614922/71538034-0ef9c480-2925-11ea-9ce2-d5aad1a459c7.png)
![Screen Shot 2019-12-28 at 03 46 38](https://user-images.githubusercontent.com/58614922/71538040-1a4cf000-2925-11ea-9144-b48360c3c6e9.png)
![Screen Shot 2019-12-28 at 03 46 48](https://user-images.githubusercontent.com/58614922/71538042-1ae58680-2925-11ea-947f-5092d98bd372.png)

**Comment by ZebingZong** [comment]
You don't need to add `AFNetworking`, it is just an example to explain how to specify the schema in podfile in the link. In your case, you just need to change all `5.6` to `5.13.1` and run `pod install` again.

**Comment by kamalkam** [comment]
i tried that solution i opened the podfile"text editor" and i changed the version to 5.13.1 and locate the project on terminal by drag and drop it "cd" and when i try to build same error shows 
after that i ve tried to add the 'FBSDKCorekit' Library into my project but same Probleme 
here are some screenshoots
![Screen Shot 2019-12-29 at 18 46 56](https://user-images.githubusercontent.com/58614922/71560547-a49f6c00-2a6b-11ea-812f-e4fc720065e4.png)

![Screen Shot 2019-12-29 at 17 51 52](https://user-images.githubusercontent.com/58614922/71560509-12976380-2a6b-11ea-87cc-17ac702f103f.png)

here is the library that i added to the project 
![Screen Shot 2019-12-29 at 18 36 54](https://user-images.githubusercontent.com/58614922/71560510-132ffa00-2a6b-11ea-84ba-cb9305e08b29.png)
![Screen Shot 2019-12-29 at 18 37 06](https://user-images.githubusercontent.com/58614922/71560511-132ffa00-2a6b-11ea-8278-251d97b4f30f.png)
![Screen Shot 2019-12-29 at 18 48 26](https://user-images.githubusercontent.com/58614922/71560555-dc0e1880-2a6b-11ea-939a-5d023b29aa4e.png)

**Comment by ZebingZong** [comment]
Did you run ‘pod install’ in your terminal after you change the podfile?

**Comment by kamalkam** [comment]
Yes i run pod install after i changed the podfile but same error

**Comment by jscoobysnack** [comment]
I'm seeing this too.

**Comment by ZebingZong** [comment]
@kamalkam @jscoobysnack does your project use Swift or Objective-C interface of the SDK?

**Comment by kamalkam** [comment]
My project is game i program it with c# in unity 
After that i added the Facebook sdk to it .. And i build it for xcode 
No it doesn't use objective-c or swift

**Comment by jscoobysnack** [comment]
@ZebingZong We are using Objective-C.

**Comment by jscoobysnack** [comment]
It seems that the Pods project is no longer being automatically built. I look in the derived data folder for the product and none of the targets are there.

**Comment by frungillo** [comment]
I've same issue here.
Game write with unity and unable to build in XCODE due "library not found for -lFBSDKCoreKit".
I'm locked in this problem from 2 days. I've tried everything described in this post.....

**Comment by ZebingZong** [comment]
@kamalkam @jscoobysnack @frungillo what other errors messages you see beyond `Library not found ~|FBSDKCorekit`. Do it point to some specific files?

**Comment by frungillo** [comment]
@ZebingZong this is the entire text of my issue:

```
Ld /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/numbers.app/numbers normal x86_64 (in target 'Unity-iPhone' from project 'Unity-iPhone')
    cd /Users/genny/OneDrive/APK/Numbers/iOS/numbers_simulator_build
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-ios9.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator -L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/FBSDKCoreKit -L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/FBSDKLoginKit -L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/FBSDKShareKit -L/Users/genny/OneDrive/APK/Numbers/iOS/numbers_simulator_build -L/Users/genny/OneDrive/APK/Numbers/iOS/numbers_simulator_build/Libraries -F/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator -filelist /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphonesimulator/Unity-iPhone.build/Objects-normal/x86_64/numbers.LinkFileList -Xlinker -map -Xlinker /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphonesimulator/Unity-iPhone.build/numbers-LinkMap-normal-x86_64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphonesimulator/Unity-iPhone.build/Objects-normal/x86_64/numbers_lto.o -Xlinker -objc_abi_version -Xlinker 2 -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -ObjC -lFBSDKCoreKit -lFBSDKLoginKit -lFBSDKShareKit -lz -weak_framework Accelerate -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework Security -weak_framework Social -weak_framework UIKit -weak_framework CoreMotion -weak-lSystem -Wl,-undefined,dynamic_lookup -Wl,-exported_symbol,_il2cpp_\* -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphonesimulator/Unity-iPhone.build/numbers.app-Simulated.xcent -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -liPhone-lib -lil2cpp -weak_framework Metal -lPods-Unity-iPhone -Xlinker -dependency_info -Xlinker /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphonesimulator/Unity-iPhone.build/Objects-normal/x86_64/numbers_dependency_info.dat -o /Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/numbers.app/numbers

ld: warning: directory not found for option '-L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/FBSDKCoreKit'
ld: warning: directory not found for option '-L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/FBSDKLoginKit'
ld: warning: directory not found for option '-L/Users/genny/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecsnxmtxasxygqbbgkxjwmnbwayw/Build/Products/ReleaseForRunning-iphonesimulator/FBSDKShareKit'
ld: library not found for -lFBSDKCoreKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by jscoobysnack** [comment]
I checked the project settings that were generated for the Pods project and they were slightly incorrect. The Pods project was targeting different architectures so when my main project was built, it did not auto build the Pods project.

I ended up deleting all of my Pods files and starting from scratch. The one difference was I changed the podfile to: platform: ios, '9.0' instead of '11.0'. Then doing the pod init and pod install setup the projects properly for me.

**Comment by joesus** [comment]
@jscoobysnack did you happen to notice if `use_frameworks!` was commented in your previous Podfile? I did some experimenting and it seems the latest version does not work if we're not using dynamic frameworks. I wonder if pod init reset it to the default which is to use dynamic frameworks.

**Comment by ZebingZong** [comment]
@kamalkam @frungillo
can you guys try to add `use_frameworks!` after `platform :ios, '9.0'` as a new line to see whether it fixes the issue? Here is an example Podfile

```
platform :ios, '9.0'

use_frameworks!

target 'ASRIOS' do

  # Pods for ASRIOS
  pod 'FBSDKCoreKit', '5.11.1'
  pod 'FBSDKLoginKit', '5.11.1'
  pod 'FBSDKShareKit', '5.11.1'

  target 'ASRIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ASRIOSUITests' do
    # Pods for testing
  end

end
```

**Comment by ZebingZong** [comment]
@kamalkam @frungillo does the issue still happen to you guys?

**Comment by ZebingZong** [comment]
I assume this issue is fixed since no one is replying.

**Comment by willblaschko** [comment]
The fix is to manually remove the POD entry in the main package (leaving the Unity library reference). This seems like a bug with the FB SDK, it shouldn't cause a crash if included twice.

**Comment by kamalkam** [comment]
> platform :ios, '9.0'
> 
> use_frameworks!
> 
> target 'ASRIOS' do
> 
>   # Pods for ASRIOS
>   pod 'FBSDKCoreKit', '5.11.1'
>   pod 'FBSDKLoginKit', '5.11.1'
>   pod 'FBSDKShareKit', '5.11.1'
> 
>   target 'ASRIOSTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
>   target 'ASRIOSUITests' do
>     # Pods for testing
>   end
> 
> end

i still having the same error and can t find any solution for it

**Comment by natebluewizard** [comment]
Also getting this issue - any help would be appreciated, im not sure if this can be reopened or I should start another issue. 

When my Podfile is this: 

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'FBSDKCoreKit', '5.13.1'
  pod 'FBSDKLoginKit', '5.13.1'
  pod 'FBSDKShareKit', '5.13.1'
end
`
I receive the error: 

> Library not found for -lFBSDKCoreKit

When archiving in XCode 11.3.1

If i add the line: **use_frameworks!** under the **platform :ios, '9.0'** I get this error:

~/Desktop/FB2020Test-5/Libraries/FacebookSDK/SDK/Editor/iOS/FBUnitySDKDelegate.h:19:9: 'FBSDKShareKit/FBSDKShareKit.h' file not found

This is after running 'pod install --verbose' each time i modify the Podfile.

**Comment by shpen** [comment]
Having the exact same issues as mentioned above.

**Comment by abhaykap** [comment]
Me too. Having exact same issue. Any body found any solution?

**Comment by kamalkam** [comment]
https://youtu.be/nmeMHY5D4SI
I ve solved the probleme by following this tutorial until minute 7:35
I ve download the facebook sdk "version 7.15.2" from facebook sdk's library 
Delete the sdk that you are using and replace it by version 7.15.2 
And it gonna work 
I hope this help 
If you need anything just reply to this and i will show you how i solved the probleme 
Good luck

**Comment by joesus** [comment]
Please open a new issue with repro instructions and ideally a link to a sample project to help diagnose the issue.
