### ISSUE TITLE
FBSDKCoreKit causes Memory Leak

### ISSUE THREAD

**Issue by Sunrise17** [facebook/facebook-ios-sdk#1292]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues) [Issue](https://github.com/facebook/facebook-ios-sdk/pull/991/files
)

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.3.1`
- Swift Version: `5` (if issue is Swift related)
- Installation Platform & Verison:  CocoaPods 1.9.1
  - FBSDKCoreKit (6.2.0):
    - FBSDKCoreKit/Basics (= 6.2.0)
    - FBSDKCoreKit/Core (= 6.2.0)
  - FBSDKCoreKit/Basics (6.2.0)
  - FBSDKCoreKit/Core (6.2.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (6.2.0):
    - FBSDKLoginKit/Login (= 6.2.0)
  - FBSDKLoginKit/Login (6.2.0):
    - FBSDKCoreKit (~> 6.2.0)

## Expected Results

What do you expect to happen?

## Actual Results

What actually happened? Can you provide a stack trace?

In my app, user logged in with his Facebook account and as soon as he starts purchasing order, memory leaks occurred as shown in the 'Leaks' instruments below. It does not matter purchasing order completed successfully or not. It is enough to start process for leakage.
 
```
let payment = SKPayment(product: productId)
paymentQueue.add(payment)
```

<img width="995" alt="Memory_Leak" src="https://user-images.githubusercontent.com/26038249/77364667-cc018e80-6d65-11ea-995c-fd380ef1cf02.png">

## Steps to Reproduce

What are the steps necessary to reproduce this issue?

https://github.com/facebook/facebook-ios-sdk/pull/991/files
I have already updated the following line (add weak) unfortunately, it did not help.

Looking forward to get your response!

**Comment by mafaming** [comment]
I think we may have the same problem, you can try to comment out [FBSDKPaymentObserver startObservingTransactions], and then debug to see if the memory leak still exists?

**Comment by KylinChang** [comment]
The issue should be the same as https://github.com/facebook/facebook-ios-sdk/issues/1328 and is fixed in v6.4.0.

**Comment by TheSPST** [comment]
I am still facing this issue : 
Xcode Version: 12.4
Swift Version: 5 (if issue is Swift related)
Installation Platform & Verison: CocoaPods 1.9.1
FBSDKCoreKit (9.0.0):
<img width="370" alt="Screenshot 2021-03-12 at 3 44 57 PM" src="https://user-images.githubusercontent.com/9798268/110927842-25364980-834c-11eb-8aa1-e19f1768e8cb.png">
<img width="367" alt="Screenshot 2021-03-12 at 3 45 22 PM" src="https://user-images.githubusercontent.com/9798268/110927849-28313a00-834c-11eb-8f57-22ab7edbee72.png">
