### ISSUE TITLE
Crash in FBSDKRestrictiveDataFilterManager.m line 80

### ISSUE THREAD

**Issue by clayjonezie** [facebook/facebook-ios-sdk#1374]
## Checklist

- [X] I've updated to the latest released version of the SDK (we are experiencing this on an older version from previous builds, FBSDK  6.5.0. I do not know if FBSDK  6.5.2 resolves the issue.)
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.4.1`
- FBSDK  6.5.0 (at time of build)

## Goals

What do you want to achieve?

We are using FBSDK in our app as an authentication option

## Expected Results

What do you expect to happen?

I would like FBSDK to not crash

## Actual Results

What actually happened? Can you provide a stack trace?

FBSDK is crashing at a large volume.

## Steps to Reproduce

What are the steps necessary to reproduce this issue?

I'm not sure yet, this is happening intermittently (but at a high volume) in the field. 

## Code Samples & Details

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1a5c2896c __exceptionPreprocess
1  libobjc.A.dylib                0x1a5941028 objc_exception_throw
2  CoreFoundation                 0x1a5b26dcc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1a5c2d048 ___forwarding___
4  CoreFoundation                 0x1a5c2f3a0 _CF_forwarding_prep_0
5  FBSDKCoreKit                   0x1039830cc +[FBSDKRestrictiveDataFilterManager updateFilters:] + 80 (FBSDKRestrictiveDataFilterManager.m:80)
6  FBSDKCoreKit                   0x103985f34 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 240 (FBSDKServerConfigurationManager.m:240)
7  FBSDKCoreKit                   0x103985750 __78+[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:]_block_invoke + 161 (FBSDKServerConfigurationManager.m:161)
8  FBSDKCoreKit                   0x103969c5c -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 41 (FBSDKGraphRequestMetadata.m:41)
9  FBSDKCoreKit                   0x103967534 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 806 (FBSDKGraphRequestConnection.m:806)
10 FBSDKCoreKit                   0x103967428 -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 839 (FBSDKGraphRequestConnection.m:839)
11 FBSDKCoreKit                   0x103967038 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 788 (FBSDKGraphRequestConnection.m:788)
12 CoreFoundation                 0x1a5bfa66c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
13 CoreFoundation                 0x1a5af822c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:]
14 FBSDKCoreKit                   0x103966dfc -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 767 (FBSDKGraphRequestConnection.m:767)
15 FBSDKCoreKit                   0x1039662b0 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 634 (FBSDKGraphRequestConnection.m:634)
16 FBSDKCoreKit                   0x10396443c __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 242 (FBSDKGraphRequestConnection.m:242)
17 libdispatch.dylib              0x1a58ccb7c _dispatch_call_block_and_release
18 libdispatch.dylib              0x1a58cdfd8 _dispatch_client_callout
19 libdispatch.dylib              0x1a58d9cc8 _dispatch_main_queue_callback_4CF
20 CoreFoundation                 0x1a5ba3cc8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
21 CoreFoundation                 0x1a5b9ea24 __CFRunLoopRun
22 CoreFoundation                 0x1a5b9df40 CFRunLoopRunSpecific
23 GraphicsServices               0x1afe2e534 GSEventRunModal
24 UIKitCore                      0x1a9d29580 UIApplicationMain
25 AllTrails                      0x10233876c main + 21 (UIDevice+Storage.swift:21)
26 libdyld.dylib                  0x1a5a1ce18 start
```

**Comment by mmdock** [comment]
similar crash log: SDK version 5.6.0

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1a5d4c96c __exceptionPreprocess
1  libobjc.A.dylib                0x1a5a65028 objc_exception_throw
2  CoreFoundation                 0x1a5c4adcc -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1a5d51048 ___forwarding___
4  CoreFoundation                 0x1a5d533a0 _CF_forwarding_prep_0
5  FBSDKCoreKit                   0x10174a2e0 +[FBSDKRestrictiveDataFilterManager updateFilters:] + 68 (FBSDKRestrictiveDataFilterManager.m:68)
6  FBSDKCoreKit                   0x10174cbac +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 258 (FBSDKServerConfigurationManager.m:258)
7  FBSDKCoreKit                   0x10174c418 __78+[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:]_block_invoke + 162 (FBSDKServerConfigurationManager.m:162)
8  FBSDKCoreKit                   0x10173c740 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 41 (FBSDKGraphRequestMetadata.m:41)
9  FBSDKCoreKit                   0x10173a030 __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 801 (FBSDKGraphRequestConnection.m:801)
10 FBSDKCoreKit                   0x101739f24 -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 834 (FBSDKGraphRequestConnection.m:834)
11 FBSDKCoreKit                   0x101739b34 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 783 (FBSDKGraphRequestConnection.m:783)
12 CoreFoundation                 0x1a5d1e66c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
13 CoreFoundation                 0x1a5c1c22c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:]
14 FBSDKCoreKit                   0x1017398f8 -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 762 (FBSDKGraphRequestConnection.m:762)
15 FBSDKCoreKit                   0x101738db4 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 629 (FBSDKGraphRequestConnection.m:629)
16 FBSDKCoreKit                   0x101736f90 __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 242 (FBSDKGraphRequestConnection.m:242)
17 libdispatch.dylib              0x1a59f0b7c _dispatch_call_block_and_release
18 libdispatch.dylib              0x1a59f1fd8 _dispatch_client_callout
19 libdispatch.dylib              0x1a59fdcc8 _dispatch_main_queue_callback_4CF
20 CoreFoundation                 0x1a5cc7cc8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
21 CoreFoundation                 0x1a5cc2a24 __CFRunLoopRun
22 CoreFoundation                 0x1a5cc1f40 CFRunLoopRunSpecific
23 GraphicsServices               0x1aff52534 GSEventRunModal
24 UIKitCore                      0x1a9e4d580 UIApplicationMain
25 Her                            0x10008b8e8 main + 11 (main.swift:11)
26 libdyld.dylib                  0x1a5b40e18 start

**Comment by ericrwolfe** [comment]
I'm also seeing a large spike in crashes in the past two hours with the same stack trace. FBSDKCoreKit 6.0.0, Xcode 11.3.1.

**Comment by hberberoglu** [comment]
We are also experiencing this. It started suddenly about ~1 hour ago.

**Comment by tianqibt** [comment]
Server side change is already reverted. The crash will vanish.

**Comment by snowtema** [comment]
The same problem. My app crashing on live users...

**Comment by kevinmun** [comment]
Also experiencing huge amount of crashes, still persisting

**Comment by rromanchuk** [comment]
this again

**Comment by tianqibt** [comment]
The change needs a some time to be propagated to all server. Some apps already seen the crash stopped. We also turned off the feature. It will be effective within a few minutes.

**Comment by kevinmun** [comment]
let's merge this into https://github.com/facebook/facebook-ios-sdk/issues/1373

**Comment by Yelles** [comment]
many apps (Soptify, Viber, etc) are crashing right now... Seems to be a Facebook related bug

**Comment by lucasv-takelessons** [comment]
We are also affected by this. Please move slower and break less things. Thank you.

**Comment by johnkassebaum** [comment]
What parameterizes 'few' for you?

**Comment by pangia** [comment]
crashing our entire userbase.

**Comment by johnkassebaum** [comment]
Ours too

**Comment by willswire** [comment]
Pinterest, GroupMe apps crashing on launch.

Also, **_huge_** iCloud outage right now - mail hasn't been delivered since 6 PM EST yesterday!! Not sure if it's related or not.

**Comment by andyjohns** [comment]
Yeah, same here. All users regardless if they use FB to login or not.

**Comment by rromanchuk** [comment]
this is the second time now this SDK has deadmanswitched because of a remote config. I can make my own branching mistakes i dont need additional. Not trying to pile on, but this is not the first time you guys have bricked apps due to release management.  It feels a little more nefarious than your typical "server changed response and model now breaks".

**Comment by juanchoabdon** [comment]
Same error here!

**Comment by johnkassebaum** [comment]
Still crashing 30 minutes after your revert. Are you sure you reverted the right thing?

**Comment by daniel-beard** [comment]
@tianqibt "a few minutes" isn't really an acceptable response for a crash that's taken down our entire userbase. Still crashing for me

**Comment by AndrewYab** [comment]
Are you sure this has been reverted correctly? Our apps are still crashing...

**Comment by DanielRaouf** [comment]
Affected by this as well. That is very urgent.

**Comment by ArielDemarco** [comment]
> The change needs a some time to be propagated to all server. Some apps already seen the crash stopped. We also turned off the feature. It will be effective within a few minutes.

How much time shall we consider "normal" to wait?

**Comment by bruno1308** [comment]
Don't fire the intern! We all make mistakes!!

**Comment by tinder-nathanglass** [comment]
Crashing on launch! Please address!

**Comment by marcoviz** [comment]
Same here!

**Comment by alfonsomestre** [comment]
Same!

**Comment by Kastet** [comment]
This is insane, half of the apps on my phone aren't launching!

**Comment by AndrewYab** [comment]
Our apps are still crashing.  This is unbelievable.  Please find a fix urgently!

**Comment by scf4** [comment]
lefb-pad

**Comment by tinder-maxwellelliott** [comment]
> Server side change is already reverted. The crash will vanish.

TLDR; it didn't stop crashing

**Comment by PascalJedi** [comment]
Is the new slogan,  
"Move fast and break the whole mobile iOS app ecosystem!"

**Comment by AustinConlon** [comment]
[Life imitating art](https://youtu.be/oaqHdULqet0?t=45).

**Comment by krunalsshah** [comment]
Hey please treat this is as a pandemic, the apps with iOS Facebook SDK are crashing on app launch.

**Comment by obahareth** [comment]
Our apps are still crashing as well.

**Comment by rms1000watt** [comment]
same!

**Comment by minhoryang** [comment]
Still affected

**Comment by yome** [comment]
> Server side change is already reverted. The crash will vanish.

Narrator: it didn't

**Comment by jxom** [comment]
My TikTok is crashing!

**Comment by c0x65o** [comment]
Server side change is already reverted. The crash will NOT vanish.

**Comment by jcolicchio** [comment]
Crash just vanished for me!

**Comment by geremora** [comment]
waze crashed too!

**Comment by bryankeller** [comment]
I hope this damages FB's reputation for sign on - enough that people don't even offer it as a signup option.

**Comment by rms1000watt** [comment]
how did this get into production? I'm curious of the pipelines/testing they use now...

**Comment by minelminel** [comment]
is there any way to fix everything *except* tik tok?

**Comment by obahareth** [comment]
The crash is beginning to disappear from our users now.

**Comment by liverday** [comment]
solved it here

**Comment by fossage** [comment]
Looking good here now 👍

**Comment by faridsaud** [comment]
It works now!

**Comment by DanielRaouf** [comment]
![sss](https://user-images.githubusercontent.com/17936692/81239283-ade5aa00-9004-11ea-9234-342d941c2039.jpg)

**Comment by AustinConlon** [comment]
_Tim Cook calls Mark Zuckerberg_

_Mark picks up_

Tim: "**GOOD MORNING!**"

**Comment by KeepBotting** [comment]
spy apps with spy sdks embedded crashing
probably deserved

**Comment by MeGaPk** [comment]
Same here :D

**Comment by brtylr** [comment]
Spotify still down for me for like the past 2 hours or so, the fix aint fixin' *shouts into the void*

**Comment by corecoding** [comment]
Does anyone have an official word from Facebook? It feels like a server outage on their end causing the SDK to parse an invalid payload.

**Comment by rromanchuk** [comment]
> spy apps with spy sdks embedded are crashing
> probably deserved

We get it DHH, you didnt take venture.

**Comment by v1ctormoreno** [comment]
When Facebook ruins the iOS ecosystem: part 9999 please fix this.

**Comment by risaluis** [comment]
Works!!🤣🤣

**Comment by dgutov** [comment]
I choose to think this was a good Samaritan somewhere inside FB who now let all users know which of their apps contact Facebook unconditionally during startup.

**Comment by whoisjuan** [comment]
Some poor bastard at FB right now.

![image](https://user-images.githubusercontent.com/1447283/81239862-90e0b500-8fcb-11ea-954d-c80fb5e35602.png)

**Comment by SzymonFortuna** [comment]
From the user perspective - so interesting to see Spotify crashing for me supposing I didn’t sign up with Facebook.

**Comment by dwaite** [comment]
> Edit: the world is already hard as is. Put yourself in the shoes of the team that is responsible for this. They must be stressed a.f. knowing that they are crashing the whole iOS ecosystem.
> So stop pressuring them and give them time to peacefully make their fixes. Life goes on.

They should alleviate their stress by removing the telemetry code which is causing this crash. Apps embed this library so that they can let their shared users with Facebook log in; not so that Facebook can track which native apps people are running on their phones.

**Comment by johnkassebaum** [comment]
There are easy and robust tools for guarding against an eventuality that leads to such significant damage. I, and several at my company, lost an hour+ of productivity, not to mention lost revenue for apps that couldn’t launch to sell or provide their service, or employees that depend on clients being able to order for delivery, etc.. This was no simple mistake; it had lasting damage, the least of which is our crash rate tracking dropping thru the floor. If your code can cause this much damage, that makes you a very large liability.

**Comment by kodaewon** [comment]
Do you know exactly what the cause of the crash is?

**Comment by DirtySoc** [comment]
I know this is an unpopular opinion but....

https://github.com/facebook/facebook-ios-sdk/blob/9042193ae6f0c2dc8009b65071cf53d434339004/LICENSE#L12

**Comment by lucas-tl** [comment]
> Do you know exactly what the cause of the crash is?

They aren't checking for nil against a dictionary key. Pretty much CS 101 stuff.
Oh and they're exchanging data with their servers. Without being explicit about this. During the host app launch process :)

**Comment by giankotarola** [comment]
I have updated my ios phone to V13.4.1 and Spotify was back as many other apps.

**Comment by lucas-tl** [comment]
> I have updated my ios phone to V13.4.1 and Spotify was back as many other apps.

This has nothing to do with the actual update you just did. It's just that the fix they pushed takes some time to propagate. YMMV.

**Comment by ColdGrub1384** [comment]
Well, let’s now use `dlopen` since now so the entire app doesn’t crash when the framework crash 😂

**Comment by NSKevin** [comment]
This crash is just like Google Map's crash a faw days before. Backend data error..........
We should make the third-part lib to be plugin, so we can shut them down online : ]

**Comment by ourway** [comment]
I still don't understand why my Spotify was crashing. I don't use Facebook!

Probably the last working day for a release management team leader. Happily the poor guy is not a pilot, or 300 dead bodies could be the result.

I am sure we are expecting urgent response from Facebook. Personally I am deprecating FB support. Bare email/pass is much reliable than this shit.

**Comment by yolarrydabomb** [comment]
> I still don't understand why my Spotify was crashing. I don't use Facebook!

Because their crap code is wrap around the app

**Comment by giankotarola** [comment]
> > I have updated my ios phone to V13.4.1 and Spotify was back as many other apps.
> 
> This has nothing to do with the actual update you just did. It's just that the fix they pushed takes some time to propagate. YMMV.

@lucas-tl  Weird 🤔. I was with two ios devices, both with the apps crashing issue, one was updated to verify if the ios version update could be resolve. When I saw that after the update the apps were back, I updated the other one(that continues with the issues) and then apps were back too. It is Just is my experience with the apps crashing problem ✌️

**Comment by NikxDa** [comment]
Give these guys a break. I'm sure whoever is responsible is having a super shitty day and we all make mistakes. Given the size of this piece of software, bugs of this scale are rather rare and it was resolved pretty quickly given that those changes need time to propagate as well.

**Comment by lucas-tl** [comment]
> > > I have updated my ios phone to V13.4.1 and Spotify was back as many other apps.
> > 
> > 
> > This has nothing to do with the actual update you just did. It's just that the fix they pushed takes some time to propagate. YMMV.
> 
> @lucas-tl Weird 🤔. I was with two ios devices, both with the apps crashing issue, one was updated to verify if the ios version update could be resolve. When I saw that after the update the apps were back, I updated the other one(that continues with the issues) and then apps were back too. It is Just is my experience with the apps crashing problem ✌️

Yeah I get that. Keep in mind chances are your device flushed DNS cache or something in that process. I can tell you my device went back to normal without doing any update or anything.

**Comment by catSIXe** [comment]
> Give these guys a break. I'm sure whoever is responsible is having a super shitty day and we all make mistakes. Not a good look calling for the firing of anyone here. Given the size of this piece of software, bugs of this scale are rather rare and it was resolved pretty quickly given that those changes need time to propagate as well.

Still does not change the fact, that the Spy Code is causing Problems... Lets just remove it...

**Comment by NikxDa** [comment]
> > Give these guys a break. I'm sure whoever is responsible is having a super shitty day and we all make mistakes. Not a good look calling for the firing of anyone here. Given the size of this piece of software, bugs of this scale are rather rare and it was resolved pretty quickly given that those changes need time to propagate as well.
> 
> Still does not change the fact, that the Spy Code is causing Problems... Lets just remove it...

I agree but would still argue that this is a different argument altogether :)

**Comment by hexafraction** [comment]
Can we get a root cause and changes to workflow/testing/process/design to prevent a recurrence of similar issues?

**Comment by dfault-user** [comment]
this entire thread has me cackling

**Comment by austinheap** [comment]
> Give these guys a break. I'm sure whoever is responsible is having a super shitty day and we all make mistakes. Not a good look calling for the firing of anyone here. Given the size of this piece of software, bugs of this scale are rather rare and it was resolved pretty quickly given that those changes need time to propagate as well.

100% agree -- anyone responsible for SLAs is presumably mature enough to understand this. It is, though, A-grade press fodder 😂

**Comment by CoCoKit** [comment]
启动后你他娘的瞎更新啥？能不能安分一点儿？？？

**Comment by trodick** [comment]
Let me just chime in here. As somebody who has had experience, albeit limited, writing software that depends on third-party libraries, this could have been gracefully avoided with better exception handling in the calling code. Anything that is doing something with a server connection should probably be wrapped in a try...catch block. That way, if something upstream does break, or the calling code receives an unexpected value, it can handle the failure without segfaulting and dumping core. I know it's probably a pain in the behind to start wrapping everything in exception-handling code, but it'll save everyone's bacon later on.

**Comment by 0xmohit** [comment]
Every app you run
I'll be watching you

**Comment by pangia** [comment]
> Let me just chime in here. As somebody who has had experience, albeit limited, writing software that depends on third-party libraries, this could have been gracefully avoided with better exception handling in the calling code. Anything that is doing something with a server connection should probably be wrapped in a try...catch block. That way, if something upstream does break, or the calling code receives an unexpected value, it can handle the failure without segfaulting and dumping core. I know it's probably a pain in the behind to start wrapping everything in exception-handling code, but it'll save everyone's bacon later on.

not true in this case. no try/catch block and the entire thing was encapsulated in their SDK.

**Comment by JoshCheek** [comment]
@trodick that's what I was originally thinking, but it sounds like their code may be calling out to FB when it gets loaded, without the calling code even being aware of this. That's based on this comment: https://github.com/facebook/facebook-ios-sdk/issues/1374#issuecomment-624973970 If so, that's a fkn nefarious thing for their code to do, and calling it "spyware" is almost certainly justified, and wiping out everyone else's apps is to be expected. Again, if so, then the problem isn't their release management, it's the nefarious way they wrote their SDK. 🤔 but, I'm not too confident in that comment, because how would it know which credentials to use when talking to FB on startup?

**Comment by NSKevin** [comment]
> 启动后你他娘的瞎更新啥？能不能安分一点儿？？？

Please be rational  :  ]

**Comment by FanYouXin** [comment]
A spooky morning！

**Comment by trodick** [comment]
@JoshCheek Hmmm, but that does make me wonder: Given that the library is open-source, shouldn't a security researcher have already found out what it was doing? Or do you think this is something on the remote end and the client library was receiving an inappropriate value that wasn't handled right? If so, then it's both the client and the API endpoint.

**Comment by AustinConlon** [comment]
Great part of the WWDC session Binary Frameworks in Swift worth watching: https://developer.apple.com/videos/play/wwdc2019/416/?time=438.

**Comment by ScottORLY** [comment]
You can disable auto logging app events.
<img width="840" alt="Screen Shot 2020-05-06 at 7 47 22 PM" src="https://user-images.githubusercontent.com/13109315/81249149-ce950c00-8fd2-11ea-9e6d-23f1b1239148.png">
https://developers.facebook.com/docs/app-events/getting-started-app-events-ios

**Comment by megs-seek** [comment]
> You can disable auto logging app events.
> <img alt="Screen Shot 2020-05-06 at 7 47 22 PM" width="840" src="https://user-images.githubusercontent.com/13109315/81249149-ce950c00-8fd2-11ea-9e6d-23f1b1239148.png">
> https://developers.facebook.com/docs/app-events/getting-started-app-events-ios

Is the logging what is causing the crash? i.e. would this fix the issue?

**Comment by WeGamers** [comment]
Same ！

**Comment by ScottORLY** [comment]
> Is the logging what is causing the crash? i.e. would this fix the issue?

Maybe 🤷‍♂️ I think the offending line has to do with the event logging and it seems reasonable to assume that it would ameliorate the issue but I haven't verified it myself.

Is your app still crashing?

**Comment by megs-seek** [comment]
> > Is the logging what is causing the crash? i.e. would this fix the issue?
> 
> Maybe 🤷‍♂️ From what I understand the offending line has to do with the event logging and it seems reasonable to assume that it would ameliorate the issue but I haven't verified it myself.
> 
> Is your app still crashing?

were seeing the crash rate about 1/5 what it was 2 hours ago, but there are still significant amount of crashes. still deciding whether its worth releasing a bug fix or waiting for the problem to disappear.. my guess is just to wait

**Comment by ademirev** [comment]
Seems that the issue is resolved; Spotify and GroupMe, etc. are all up and running on my end.

**Comment by ISusu** [comment]
How can i fix this issue?

**Comment by ISusu** [comment]
Four hours ago, the crash rate of my app reached 18%, then it returned to normal, and now it's 15%. Give me a chance, the boss is going to fire me. What should I do?

**Comment by allenday** [comment]
> > Edit: the world is already hard as is. Put yourself in the shoes of the team that is responsible for this. They must be stressed a.f. knowing that they are crashing the whole iOS ecosystem.
> > So stop pressuring them and give them time to peacefully make their fixes. Life goes on.
> 
> They should alleviate their stress by removing the telemetry code which is causing this crash. Apps embed this library so that they can let their shared users with Facebook log in; not so that Facebook can track which native apps people are running on their phones.

No, they shouldn't. Facebook has a fiduciary responsibility to their shareholders to monetize surveillance of user behavior.

**Comment by Shing-Ho** [comment]
👊

**Comment by MebDevelop** [comment]
👊

**Comment by allenday** [comment]
🤜💥🤛

**Comment by ISusu** [comment]
It returned to normal now.

**Comment by jeannekamikaze** [comment]
Just remove the spyware from your software and it will all start working again.

**Comment by kazzkiq** [comment]
Are we ready to ask the real questions here?

Why the heck does Facebook do unwanted requests during my apps startup? What kind of info are they sending back to their servers?

**Comment by poonam-bhadikar** [comment]
Is this issue fixed now?

**Comment by Kingson** [comment]
> 启动后你他娘的瞎更新啥？能不能安分一点儿？？？

我们的所有App都中招

**Comment by Roxasora** [comment]
Could someone working for facebook SDK stand out and explain this??😢😢😢😢 This is a real tragedy!! We need to know what happened and why it happened!!😤😤😤😤

**Comment by andyjohns** [comment]
If you're really curious about what they're doing, just capture it with Charles Proxy. On my app it looks like they're making four calls, three POSTs and a GET, to graph.facebook.com. Haven't spent any time analyzing it, but it looks like they're sending some basic info about the running environment. I see the SDK version in there, our SDK key. Looks like configuration data coming back. Analytics tracking I expect....

**Comment by so898** [comment]
Maybe it's time to reverse-engineering FB SDK and making a real open source FB login SDK.

**Comment by krunalsshah** [comment]
Our iOS app is still reporting crashes, for others, have your app's recovered 100%?
Snippet from our error monitoring & reporting tool, still alerting the crash. 

```NSInvalidArgumentExceptionFBSDKRestrictiveDataFilterManager.m:66
-[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1e8da5d00
```
Anyone from the Facebook core team can provide a detailed analysis of the problem? 

The question to the Facebook core team
> Can we have a configuration to lazy load the initialization only when the app feature requires it?

**Comment by mrpuzzler** [comment]
Same here:
`
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x182aa4a48 __exceptionPreprocess
1  libobjc.A.dylib                0x1827cbfa4 objc_exception_throw
2  CoreFoundation                 0x1829a85a8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x182aa8af4 ___forwarding___
4  CoreFoundation                 0x182aaaa7c _CF_forwarding_prep_0
5  Game                           0x10058c31c +[FBSDKRestrictiveDataFilterManager updateFilters:] + 80 (FBSDKRestrictiveDataFilterManager.m:80)
6  Game                           0x10058eda8 +[FBSDKServerConfigurationManager processLoadRequestResponse:error:appID:] + 241 (FBSDKServerConfigurationManager.m:241)
7  Game                           0x10058e600 __78+[FBSDKServerConfigurationManager loadServerConfigurationWithCompletionBlock:]_block_invoke + 163 (FBSDKServerConfigurationManager.m:163)
8  Game                           0x1005783c0 -[FBSDKGraphRequestMetadata invokeCompletionHandlerForConnection:withResults:error:] + 41 (FBSDKGraphRequestMetadata.m:41)
9  Game                           0x100575cdc __82-[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:]_block_invoke + 806 (FBSDKGraphRequestConnection.m:806)
10 Game                           0x100575bd0 -[FBSDKGraphRequestConnection processResultBody:error:metadata:canNotifyDelegate:] + 839 (FBSDKGraphRequestConnection.m:839)
11 Game                           0x1005757e0 __64-[FBSDKGraphRequestConnection completeWithResults:networkError:]_block_invoke + 788 (FBSDKGraphRequestConnection.m:788)
12 CoreFoundation                 0x182a7795c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
13 CoreFoundation                 0x18297aed0 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:]
14 Game                           0x1005755a4 -[FBSDKGraphRequestConnection completeWithResults:networkError:] + 767 (FBSDKGraphRequestConnection.m:767)
15 Game                           0x100574a60 -[FBSDKGraphRequestConnection completeFBSDKURLSessionWithResponse:data:networkError:] + 634 (FBSDKGraphRequestConnection.m:634)
16 Game                           0x100572c9c __36-[FBSDKGraphRequestConnection start]_block_invoke_3 + 242 (FBSDKGraphRequestConnection.m:242)
`

**Comment by freezy7** [comment]
The crash is still report, and it make the firebase could not refresh out new data. 😠

**Comment by mattiacantalu** [comment]
Same situation here.. We're using `'FBSDKLoginKit', '5.15.1'` and the crash is reported live on our users! Please Facebook, provide a fix asap 😰

**Comment by bhvk** [comment]
> Are we ready to ask the real questions here?
> 
> Why the heck does Facebook do unwanted requests during my apps startup? What kind of info are they sending back to their servers?

Checkout Off-Facebook activity logging : https://en-gb.facebook.com/off-facebook-activity 
They are going to be the new NSA I presume.

**Comment by BradKwon** [comment]
I've got some crash report of this last night but it seems it looks stable although I have tried to log in via Facebook app once. However, better to keep monitoring it since there is not clear fix yet.
My app uses SDK v5.6.0 and logged in from Germany.

**Comment by sree127** [comment]
Same. Looks "kinda" stable now. No crashes in the last 60 mins at least. 👀

**Comment by pepejeria** [comment]
https://www.theverge.com/2020/5/6/21250023/facebook-sdk-login-spotify-tinder-tiktok-ios-iphone-crash

“Earlier today, a new release of Facebook included a change that triggered crashes for some users in some apps using the Facebook iOS SDK,” a Facebook spokesperson said in a statement to The Verge. “We identified the issue quickly and resolved it. We apologize for any inconvenience.”

**Comment by mqlsq** [comment]
> > 启动后你他娘的瞎更新啥？能不能安分一点儿？？？
> 
> 我们的所有App都中招

我们也是，损失惨重

**Comment by mifi** [comment]
This is why I like to keep the number of native dependencies in my react-native apps to the minimum

**Comment by syedanabimam** [comment]
![image](https://user-images.githubusercontent.com/8035090/81275837-37ef3c00-9020-11ea-8780-c3211c823146.png)

**Comment by elecCore** [comment]
> > > 启动后你他娘的瞎更新啥？能不能安分一点儿？？？
> > 
> > 
> > 我们的所有App都中招
> 
> 我们也是，损失惨重

心都碎了，苦苦维持线上1‰的崩溃率，一个更新给我拉升了2%纯涨了2%！是2%！不是2‰！

**Comment by AustinConlon** [comment]
This thread should be canonized in the Computer History Museum.

**Comment by DeepakTivari** [comment]
Facebook and their spywares

**Comment by dongshuju** [comment]
> > > > 启动后你他娘的瞎更新啥？能不能安分一点儿？？？
> > > 
> > > 
> > > 我们的所有App都中招
> > 
> > 
> > 我们也是，损失惨重
> 
> 心都碎了，苦苦维持线上1‰的崩溃率，一个更新给我拉升了2%纯涨了2%！是2%！不是2‰！

一夜回到解放前

**Comment by AustinConlon** [comment]
In 2014 Facebook updated the company mantra and it was a wonderful thought. Any chance we could have it added to this repository's README?

![tumblr_n4uvx6ZXSk1sxqyhyo1_1280](https://user-images.githubusercontent.com/1305957/81283194-18044c00-9011-11ea-9f5e-cc7dd456a1f4.jpg)

**Comment by santaasus** [comment]
I have some issue in restrictiveParams[eventName][@"is_deprecated_event"], but there isn't condition for dictionary like [restrictiveParams objectForKey], there is force unwrap by key

**Comment by AustinConlon** [comment]
All rise for the [Facebook iOS SDK anthem.](https://www.youtube.com/watch?v=2Cx-LIbsgq4&feature=youtu.be&t=53)

> Anti-Patterns
> Coding practices you should avoid
> Anti-Patterns
> So your app don’t crater like a meteoroid
> 
> Whether you’re a newbie or here since NeXTSTEP 3.3
> There’s a chance you’ve picked up some bad habits
> So take my advice, make your code play nice
> Or the bugs will multiply like rabbits
> Doo, doo da doo doo
> 
> Anti-Patterns
> Yeah, you know they’re gonna bite you somewhere down the line
> Anti-Patterns
> Even if the code seems to work at the time

**Comment by Tibimac** [comment]
The code where crash occurs is quite different in recents versions of the FBSDK, so yes there's is a retro-compatibility problem in the config sent by  FB servers but maybe the issue could also be solved by and update of the SDK. Indeed it seems that the key `is_deprecated_event` is no longer checked in code of recents versions.

<img width="1377" alt="Capture d’écran 2020-05-07 à 13 36 49" src="https://user-images.githubusercontent.com/7674218/81290399-495c3680-9068-11ea-9723-b0c7151d8190.png">
<img width="1259" alt="Capture d’écran 2020-05-07 à 13 37 38" src="https://user-images.githubusercontent.com/7674218/81290405-4d885400-9068-11ea-8bd2-4409d27ec6c7.png">
<img width="578" alt="Capture d’écran 2020-05-07 à 13 38 01" src="https://user-images.githubusercontent.com/7674218/81290412-4eb98100-9068-11ea-9952-5658c3f78cec.png">

**Comment by RubenKelevra** [comment]
Quite interesting how many apps report each startup to Facebook... probably with the user ID.

You should consider to remove the Facebook functionality from your app entirely.

**Comment by balazserd** [comment]
> Quite interesting how many apps report each startup to Facebook... probably with the user ID.
> 
> You should consider to remove the Facebook functionality from your app entirely.

Yup. If you actually look at what Facebook does is it immediately sends all device info + carrier and also adds an advertisement ID.

I bet a lot of apps don't disclose this information in their privacy policies.

**Comment by PatoGuereque** [comment]
I don't know what's scarier, the fact that this basically acted as a remote kill switch for hundreds of apps or that the SDK _silently_ sends data on startup

**Comment by allenday** [comment]
> Maybe it's time to reverse-engineering FB SDK and making a real open source FB login SDK.

Maybe it's time that we take responsibility for managing our own private keys and move beyond SSO services for personal data.

**Comment by ArtFeel** [comment]
@balazserd It also swizzle all your UIView, UITextField, UIControl, etc., and add StoreKit observer, to know all about what your users see and theirs purchases.

**Comment by allenday** [comment]
> I don't know what's scarier, the fact that this basically acted as a remote kill switch for hundreds of apps or that the SDK _silently_ sends data on startup

The functional code should be scary to you.

The kill switch should be scary to FB. 

The latter because it raised FB's intentional behavior of harvesting user data to the level of awareness of developers.

**Comment by niruix** [comment]
> In 2014 Facebook updated the company mantra and it was a wonderful thought. Any chance we could have it added to this repository's README?
> 
> ![tumblr_n4uvx6ZXSk1sxqyhyo1_1280](https://user-images.githubusercontent.com/1305957/81283194-18044c00-9011-11ea-9f5e-cc7dd456a1f4.jpg)

The app crashed while trying to output _INFRASTRUCTURE_.

**Comment by CailinPitt** [comment]
This was a real eye-opening experience. Might have to stop using a lot of the apps that have been communicating with Facebook without my knowledge.

**Comment by behdaad** [comment]
Let this be a lesson to all of us. We all make mistakes, even the best of us. Stay safe, stay humble.

**Comment by petermjones** [comment]
Facebook fixing the server configuration is not good enough.  At least two things must be done:
1. SDK should not crash, regardless of what information comes back from Facebook's servers.
2. Full transparency as to why it is connecting and what information is being shared.

As App writers, we're deliberately ignoring the fact that the more dependencies you have, the more brittle our systems become.  We need to re-think that strategy.

**Comment by KingTerrytheTerrible** [comment]
Stop using Facebook.

**Comment by tianqibt** [comment]
A new release of Facebook included a change that triggered crashes for some users in some apps using the Facebook iOS SDK. We identified the issue quickly and resolved it. We apologize for any inconvenience

**Comment by krunalsshah** [comment]
Thanks for fixing the issue. 

Our iOS app is still reporting crashes, for others, not sure if the apps have recovered 100%? @tianqibt what do your monitoring tools show?

We'd appreciate more details. 

- Why does the initialization call fire at launch time, and not lazily loaded?
- Is there a way to configure the SDK such that it could lazily load?  And could that change propogate to `react-native-fbsdk`?

Snippet from our error monitoring & reporting tool, still alerting the crash.

```
-[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1e8da5d00
```

**Comment by timuren** [comment]
How many apps out there still appear to be impacted?

**Comment by akhilpothana** [comment]
> Facebook fixing the server configuration is not good enough. At least two things must be done:
> 
> 1. SDK should not crash, regardless of what information comes back from Facebook's servers.
> 2. Full transparency as to why it is connecting and what information is being shared.
> 
> As App writers, we're deliberately ignoring the fact that the more dependencies you have, the more brittle our systems become. We need to re-think that strategy.

@petermjones exactly! especially the fact that even a large well versed tech company's sdk can break

**Comment by lordzsolt** [comment]
> Thanks for fixing the issue.
> 
> Our iOS app is still reporting crashes, for others, not sure if the apps have recovered 100%? @tianqibt what do your monitoring tools show?
> 
> We'd appreciate more details.
> 
> * Why does the initialization call fire at launch time, and not lazily loaded?
> * Is there a way to configure the SDK such that it could lazily load?  And could that change propogate to `react-native-fbsdk`?
> 
> Snippet from our error monitoring & reporting tool, still alerting the crash.
> 
> ```
> -[__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1e8da5d00
> ```

How would you expect Facebook to track all your users if they don't fire at first launch?

**Comment by virtadpt** [comment]
> They are going to be the new NSA I presume.

"Going to be?"

**Comment by kconner** [comment]
> A new release of Facebook included a change that triggered crashes for some users in some apps using the Facebook iOS SDK. We identified the issue quickly and resolved it. We apologize for any inconvenience

To be clear, are you saying this was fixed on the server side, and deployed apps should no longer exhibit the crash? It's not necessary to update apps with a new Facebook SDK version?
