### ISSUE TITLE
Unable to use the prebuilt frameworks from the Releases section

### ISSUE THREAD

**Issue by gui17aume** [facebook/facebook-ios-sdk#1380]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

- Xcode Version: `11.4.1`
- Swift Version: `5.2.2`
- Installation Platform & Version: `Manual` version `7.0.0`

## Goals

I want to use manually the prebuilt frameworks provided under the Releases section of the GitHub project page.

## Expected Results

I add the frameworks to my project and it builds.

## Actual Results

An error occurs during the build.

When building for a simulator target: 
`AppDelegate.swift:10:8: Could not find module 'FBSDKShareKit' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7`

When building for a device target:
`AppDelegate.swift:10:8: Module compiled with Swift 5.1 cannot be imported by the Swift 5.2.2 compiler: FBSDKShareKit.framework/Modules/FBSDKShareKit.swiftmodule/arm64-apple-ios.swiftmodule`

## Steps to Reproduce

- Create a new iOS project in Xcode
  - Use Swift as main language
  - Xcode version must differ from the one used by the Facebook team to produce the prebuilt frameworks
- Download some prebuilt frameworks from the Release 7.0.0 available on GitHub, I used FBSDKShareKit and FBSDKCoreKit
- Add the frameworks to the project
- In the AppDelegate, import the framework, in my case `import FBSDKShareKit`
- Try to build the project with a simulator and a device target

## Code Samples & Details

The build scripts used to generate the universal frameworks seem to miss 2 things:

- They don't specify the fact that the products are build for distribution, so the .swiftinterface files are not generated (`build-universal-framework.sh` and `build-universal-tvos-framework.sh`)
  - adding `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` to the `xcodebuild` commands should fix this issue

- They don't copy to the universal framework the swiftmodule files produced during the simulator build (`build-universal-framework.sh` only)
  - adding this copy step to the script seems to fix the issue:
```sh
rsync -a "${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/${PROJECT_NAME}.framework/Modules/${PROJECT_NAME}.swiftmodule/" "${UNIVERSAL_BUILD_FOLDER}/${PROJECT_NAME}.framework/Modules/${PROJECT_NAME}.swiftmodule"
```

**Comment by joesus** [comment]
Fixed. Will be in next release. Thank you!!!

**Comment by psolt-gpsw** [comment]
I'm still not able to use the pre-built frameworks, `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` is not set in the SDK targets. For the 9.0.1 release I get the error:
            
        Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.2 compiler


I had to manually build with Carthage and edit the project files:

1. Build Facebook with Carthage (Change the version to latest release version)

        brew install carthage
        echo 'github "facebook/facebook-ios-sdk" == 9.0.1' > Cartfile
        carthage update

2. Edit Xcode Project to enable Module Stability
    
    1. Open the Facebook workspace from Carthage
                
            open Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace
                
    2. Change each dependency framework to “Build Libraries for Distribution” to enable Module Stability.
    
            Build Libraries for Distribution (BUILD_LIBRARY_FOR_DISTRIBUTION) = YES
            
3. Build the updated project for XCFrameworks

            carthage build --use-xcframeworks
