### ISSUE TITLE
FBAudienceNetwork 5.6.0 pod install returning 500 Internal Server Error during build

### ISSUE THREAD

**Issue by jjhampton** [facebook/facebook-ios-sdk#1384]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: 11.1
- Installation Platform & Verison: Cocoapods version 1.9.1

## Goals

Install FBAudienceNetwork SDK via CocoaPods `pod install`

## Expected Results

Successful install of FBAudienceNetwork SDK.

## Actual Results
Getting a 500 Internal Server Error when building my app on CI server and the `pod install` command is ran:
```
Installing FBAudienceNetwork (5.6.0)

[!] Error installing FBAudienceNetwork
[!] /usr/local/opt/curl/bin/curl -f -L -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200514-3356-56vahd/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.6.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
##[error]The process '/usr/local/lib/ruby/gems/2.6.0/bin/pod' failed with exit code 1
```

## Steps to Reproduce

Attempt to install FBAudienceNetwork SDK via `pod install`.

**Comment by asasahary** [comment]
[diagnostics.zip](https://github.com/facebook/facebook-ios-sdk/files/4633538/diagnostics.zip)
[diagnostics.zip](https://github.com/facebook/facebook-ios-sdk/files/4633535/diagnostics.zip)

**Comment by sharoni** [comment]
Hi,

Is is an intermittent issue or does it happen 100% of the time? Just tried it and it successfully fetched **FBAaudienceNetwork** pod -

```
$ pod install    
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (5.6.0)
Installing FBSDKCoreKit (7.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
```

**Comment by jjhampton** [comment]
@sharoni It occasionally works, but just as often has a 500 Internal Server Error. On Thursday, May 15, when running the build from remote CI server, I had about 50% fails, 50% successful pod installs.

Roughly the same when running the `curl` command locally. 

Today, May 16, I've ran 4 builds on CI servers so far, and half have failed due to failing `pod install` of FBAudienceNetwork.

**Comment by tonypottera24** [comment]
Same issue on `pod 'GoogleMobileAdsMediationFacebook'`
It fetch `FBAudienceNetwork (4.99.3)` as dependency.
```
-> Installing FBAudienceNetwork (4.99.3)
     > Http download
       $ /opt/local/bin/curl -f -L -o /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/d20200516-69385-shbgss/file.zip
       https://developers.facebook.com/resources/FBAudienceNetwork-4.99.3.zip --create-dirs --netrc-optional --retry 2

    [!] Error installing FBAudienceNetwork
    [!] /opt/local/bin/curl -f -L -o /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/d20200516-69385-shbgss/file.zip
    https://developers.facebook.com/resources/FBAudienceNetwork-4.99.3.zip --create-dirs --netrc-optional --retry 2

      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0
  --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0
  0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    curl: (22) The requested URL returned error: 500 Internal Server Error
    Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
    Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0
  --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0
  0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
    curl: (22) The requested URL returned error: 500 Internal Server Error
    Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
    Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0
  --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0
  0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    curl: (22) The requested URL returned error: 500 Internal Server Error
```

**Comment by sharoni** [comment]
Thanks for reporting. We are observing some issues with CDN where FAN binary is hosted and passed this on to relevant team to have a look and resolve.

**Comment by insthync** [comment]
I'am developing game so I download FAN for Unity from Facebook Developer website, there is only 5.6.0 so when I build the project, the FAN version in Podfile will set to 5.6.0. So I try to change it to the version which available in FAN for iOS (5.8.0 / 5.9.0) then I can run pod install with FAN version 5.9.0.
So I guess that the 5.6.0 was removed.

**Comment by renattou** [comment]
We're having the same problem with FBAudienceNetwork-5.6.1. We first noticed it yesterday and it's now getting in the way of our builds :(

**Comment by renattou** [comment]
I just tested what @insthync said and in fact FBAudienceNetwork-5.9.0 always downloads successfully, while FBAudienceNetwork-5.6.1 always fails with error 500, so it doesn't seem to affect the whole CDN.

Please fix this, as simply upgrading to 5.9.0 wouldn't be desirable at this point nor justifiable.

**Comment by sharoni** [comment]
The issue should be resolved now. Please report any further errors while downloading AN SDK binary. Apologies for this breaking your CI/workflow.

**Comment by renattou** [comment]
I tried a few times and it seems to be working properly now. I'll report if it happens again.
Thank you very much @sharoni !

**Comment by arslan311** [comment]
Hi I am still having this issue while installing FBAudienceNetwork pod, it still gives following error. please guide me

[!] Error installing FBAudienceNetwork
.
.
.
.
.
curl: (22) The requested URL returned error: 500

**Comment by JamilHossain65** [comment]
I am still facing this error 
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (5.10.1)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/fx/_4psnltx6xg5r4qn0jmblxnw0000gn/T/d20200725-781-efun5l/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.10.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0.beta.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500

**Comment by DaveMariner** [comment]
Hi @sharoni:

We're also experiencing this issue with 5.10.0 and 5.10.1. It looks like it's been like that for a few days and is currently a blocker on us readying a an SKAdNetwork-compliant release build including FAN. (Or any builds including FAN, for that matter!)

Can we get an ETA on fixing this?

**Comment by sharoni** [comment]
Hi @DaveMariner, @JamilHossain65, @arslan311, sorry to hear you are experiencing this issue. Could you let us know if this is happening consistently for you?

Right now we are not observing a higher rate of 5xx responses (< 0.01%).

**Comment by DaveMariner** [comment]
Hi @sharoni. It was happening consistently for me for approx. 24 hours. It seems someone kicked the CDN since I posted...thanks for that! 

It might be worth spinning up a cron job to curl all your SDKs to catch this without us having to resort to tagging you on github. Fairly sure you can find a spare server lying around for that.  😉 

With a tad less snark....If you were only seeing that rate of 5xx (and presumably that was before you kicked your CDN) - would there be some kind of regional aspect to this issue? I'm hitting the endpoint from the EU, FYI. 

And thanks once again for fixing it.

**Comment by sharoni** [comment]
I can assure you there is a cronjob that checks this and more :) However, in has been running successfully and we have not observed any issues.

Thanks for added details, will follow up on regional side of this.

**Comment by FaisalZaheer** [comment]
```
pod install
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (5.10.1)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/_y/95kmmc3s485fw5fmqk77cwwr0000gn/T/d20200730-73910-1p0xf5j/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.10.1.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500 


[!] The Podfile contains framework or static library targets (UnityFramework), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).

```
Accessing from PK.

**Comment by augusto-garcia-playkids** [comment]
Hi, I'm having this issue here in my computer 100%, no matter the network I use (tried my home, office VPN, 3g). The error is pretty standard:

`Using AppsFlyerFramework (5.4.1)
Installing FBAudienceNetwork (5.9.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/8g/tm9m1dqn0v39747dt3cnmr680000gp/T/d20200803-7281-1i8f252/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.9.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500 
`

Other people on my company are not having issues in their respective networks.

**Comment by im-amir** [comment]
Hi, I'm having this issue here in my computer 100%, no matter the network I use. The error is pretty standard:

Using AppsFlyerFramework (5.4.1)
Installing FBAudienceNetwork (5.6.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/8g/tm9m1dqn0v39747dt3cnmr680000gp/T/d20200803-7281-1i8f252/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.9.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500

**Comment by augusto-garcia-playkids** [comment]
Also @sharoni, we noticed that the endpoint on facebook side that the people being successful are reaching is different from the endpoint from people having issues. Hit me up and I can pass you some traceroutes, maybe we can do some other tests as well. I'll avoid posting them here for privacy issues.

**Comment by AmeerEbrahim** [comment]
Did anyone come across any alternatives ?
@sharoni ?
thanks in advance !


Installing FBAudienceNetwork (5.9.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/3b/h8gsb_ss03ndfm49x4ydb9pr0000gn/T/d20200804-23451-fe4ly4/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.9.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500

**Comment by kyughost** [comment]
Hello, same issues... Changed networks and used VPN's nothing. I'm using `pod install`
<img width="1173" alt="Screen Shot 2020-08-11 at 13 40 50" src="https://user-images.githubusercontent.com/30949306/89893300-5d1fb780-dbd8-11ea-886d-17800bf9dac0.png">

**Comment by HamzaFunavry** [comment]
Facing Same issue.

**Comment by projectMontata321** [comment]
Having the exact same issue for the last couple of weeks now. It happens 100% of attempts. I tried on different computer, network, location and nothing changes.

**Comment by shardick** [comment]
5.1.0, 5.9.0, 5.10.0 fire error 500 on downloading with pod update

**Comment by aldoyh** [comment]
I solved it by simply running a VPN.

**Comment by DaveMariner** [comment]
@aldoyh : Can you give a bit more details? F.ex. - which VPN service, and what remote endpoint did you use ?

**Comment by ahmadhattab** [comment]
Same issue here, 500 error!

**Comment by ahmadhattab** [comment]
@sharoni Same issue here, 500 error!

**Comment by aldoyh** [comment]
@DaveMariner , I used the paid service ProtonVPN from Bahrain through Dubai Server.

To confirm, I switched it off, and then again same error is back!

**Comment by DaveMariner** [comment]
@aldoyh - interesting....I just tried going through our office VPN and had the same experience. On the VPN, everything is fine, going direct and I get the 500. 

@sharoni: Would there be any weird NAT/redirect/routing thing that might be causing this?

**Comment by rafalswiech3** [comment]
I can confirm it also.

After using VPN I could successfully run pod install for FBAudienceNetwork.

On direct connection error 500

**Comment by Ulanmax** [comment]
[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/bc/mmb8j6r152q8jyh5kbdp72cm0000gn/T/d20200914-15836-17dnpyn/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.10.1.zip --create-dirs --netrc-optional --retry 2

Switching to another network helped me.

**Comment by cslosiu** [comment]
Installing FBAudienceNetwork (4.26.1)

Yes, using a VPN helps while direct connection fails. Could FB explains a bit?

**Comment by sharoni** [comment]
Thanks again for reporting and apologies for a delay in response. We've pinpointed this to be related to CDN cache (lack of it to be precise) and are in progress of addressing this.

**Comment by ahmadhattab** [comment]
@sharoni any update on this issue please!.

**Comment by vkdaros** [comment]
I'm having a similar issue.
Is there any workaround for that?

`Installing FBAudienceNetwork 5.10.1 (was 5.5.1)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/s8/q5q5bsdd3fjcc0310dtbvrlm0000gq/T/d20201019-85264-13gawod/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.10.1.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500`

**Comment by gianlucaguran** [comment]
Hello!
I'm experiencing the same problem as many people who wrote above.
I tried to connect to different networks, to my company VPN, and I still get it 100% since yesterday.
Can you help/fix this pls? 
```
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
Downloading dependencies
Installing AmazonAd (3.0.0)
Installing AppLovinSDK (6.14.3)
Installing FBAudienceNetwork (5.10.1)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/_t/lyw6t8813x31r4h35nnzqwkh0000gn/T/d20201029-5889-1b7ph7f/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.10.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
....
```

**Comment by sharoni** [comment]
Thank you for your patience, the fix is being gradually rolled out. We'll keep this task open until after we can fully confirm this is no longer an issue.

**Comment by Mishgan** [comment]
Since today we get error 500 during build project with FBAudienceNetwork (5.10.1) which we use with IronSource. We didn't update any libraries during the last 7 days so the problem suddenly appeared and blocked us to release new of our product. :(
Can you please check what is going wrong? We attempt to build project with different versions of xCode (11 and 12) on Mac OS Catalina.

```
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
Downloading dependencies
Installing AdColony (4.3.1)
Installing AppLovinSDK (6.14.3)
Installing AppsFlyerFramework (6.0.7)
Installing FBAudienceNetwork (5.10.1)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/1g/9clwj3gj4f14y81b49vpjh2m0000gn/T/d20201125-59984-41sqz9/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.10.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500 


```

**Comment by Mishgan** [comment]
@sharoni Hey :) Do you have any update about the issue i mentioned at the comment above? Can you or someone else please check it?

**Comment by akorolczuk** [comment]
This still hasn't been fixed. Are you looking into this?

**Comment by juananime** [comment]
I had same problem, and I could sort it out connecting with VPN to UK and the server 500 error went away. Maybe may work for anyone else. Thanks.

**Comment by PlayaPeter** [comment]
I have the same issue (error 500) with FBAudienceNetwork 6.2.1. I'm using Unity to load the pod. My location is Germany (Europe) and my ISP is Vodafone. Apparently the download is blocked for certain locations or ISPs.

I tried a VPN like @juananime suggested and that fixed it. I used a connection via Canada to make it work.
Having to use a VPN in the build pipeline is very bad. It would be great to see a fix for this issue ASAP!

**Comment by Mishgan** [comment]
Very actual for 3rd party CI services like Unity Cloud Build. They just banned it and not able to fix it for three month. It's very frustrating to use such hacks like VPN...

**Comment by DaveMariner** [comment]
@sharoni: Can confirm that this is breaking for me also for FAN-6.2.1. I have to wonder (again) how hard it can be for a company such as Facebook to sort out an issue such as this! It's been over 9 months since this issue was first reported.

**Comment by vgorloff** [comment]
+1 Still can't download via `pod 'GoogleMobileAdsMediationFacebook', '6.2.0.0'` :0
Berlin, Germany.

**Comment by letiziapinna** [comment]
+1 Can't download via pod 'GoogleMobileAdsMediationFacebook', '6.0.0' :0
Cagliari, Italy.

**Comment by sharoni** [comment]
Thanks for baring with us. A new set of changes to address this have been deployed recently. HTTP 200 rate is stable at >99.50%. Please report if the issue happens consistently for you.

**Comment by igorvoytovich** [comment]
@sharoni 

Hello, 

Have the same error in 100% cases with 6.3.1:

![photo_2021-03-24 10 17 57](https://user-images.githubusercontent.com/47663430/112277494-7c141b00-8c8a-11eb-8e58-c8ba6a9556eb.jpeg)

**Comment by zeeshan-mehdi** [comment]
<img width="1440" alt="Screen Shot 2021-05-01 at 11 20 41 AM" src="https://user-images.githubusercontent.com/31466216/116773550-47586800-aa6f-11eb-84ed-d1b373395f37.png">
using this vpn from appstore for mac worked for me.

<img width="1440" alt="Screen Shot 2021-05-01 at 11 21 15 AM" src="https://user-images.githubusercontent.com/31466216/116773562-5b03ce80-aa6f-11eb-9af8-60d36e87513e.png">

**Comment by zeeshan-mehdi** [comment]
<img width="1440" alt="Screen Shot 2021-05-01 at 11 20 41 AM" src="https://user-images.githubusercontent.com/31466216/116773550-47586800-aa6f-11eb-84ed-d1b373395f37.png">
using this vpn from appstore for mac worked for me.

<img width="1440" alt="Screen Shot 2021-05-01 at 11 21 15 AM" src="https://user-images.githubusercontent.com/31466216/116773562-5b03ce80-aa6f-11eb-9af8-60d36e87513e.png">

**Comment by wilton1994** [comment]
Hello, I managed to solve using a VPN from the United States.
Avast SecureLine VPN. Hope I can help someone with this.

**Comment by jawwad** [comment]
I'm going to close this issue based on @sharoni's comment in https://github.com/facebook/facebook-ios-sdk/issues/1384#issuecomment-800328433

> Thanks for baring with us. A new set of changes to address this have been deployed recently. HTTP 200 rate is stable at >99.50%. Please report if the issue happens consistently for you.

Please re-open if this continues to happen.

**Comment by mackiexx** [comment]
i solved it by using https://go.onelink.me/app/c7c915fc and switching to USA server. it works 100%

**Comment by eugeniobaglieri** [comment]
I'm having this error too. Can it be solved without installing a vpn?

**Comment by mackiexx** [comment]
> I'm having this error too (Italy). Can it be solved without installing a vpn?

i'm not sure but with the vpn solved the issue for me because i tried almost everything else and it didnt work.

**Comment by DaveMariner** [comment]
@sharoni : Reopening this as it's happened to me again today. 

```
Installing FBAudienceNetwork (6.3.1)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/41/nq1m44f50xz07d3xg6ltxt84h6pw6h/T/d20211125-51501-22ttua/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-6.3.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.2 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500 



Error : iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.
```

**Comment by usmanArif22** [comment]
I had faced same issue while attempting to install pods multiple times. Now Successfully installed after setting up VPN with US location.

**Comment by scarpelini** [comment]
I've used Proton VPN protonvpn.com. The free plan provides 3 locations(the US included) but not a fast connection. However, right after you have installed the `FBAudienceNetwork ` dependency, you can switch to your regular network while the installation process is happening, once we have several dependencies to be installed after that. It worked for me pretty well.

I hope it works fine for you who are facing this issue too.

**Comment by bilalyaqoob** [comment]
@scarpelini I tried with the Proton VPN (us)and still no success

**Comment by bilalyaqoob** [comment]
I am getting the same bug, Is there any other solution?? vpn didn't solved my issue.

**Comment by JamesZhao2022** [comment]
I meet same issue with 6.9.0, does anyone know how to fix it now?
-> Installing FBAudienceNetwork (6.9.0)
 > Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/bp/gk6x6nw11t3fgx2v48__8zl00000gn/T/d20230817-1193-c1qobd/file.zip
   https://developers.facebook.com/resources/FBAudienceNetwork-6.9.0.zip --create-dirs
   --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:--  0:01:40 --:--:--     0

**Comment by scorpionate** [comment]
Same for me, randomly started occuring

_/usr/bin/curl -f -L -o /var/folders/2k/sgt2v6_135l9k0dhqwlh36rm0000gp/T/d20231006-51795-arcu2a/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-6.9.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.13.0 cocoapods-downloader/1.6.3'_

**Comment by fedoit** [comment]
I spent days trying to solve this issue. I'm from Russia. VPN didn't help. Here is what i found:

1. Notice which version of FBAudienceNetwork is required. In my case the version is 6.14.0
2. Download FBAudienceNetwork-6.14.0.zip from here: https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/add-sdk
3. Host the file somewhere to have a download link like: https://YOURDOMAINNAME.com/FBAudienceNetwork-6.14.0.zip
4. Google the phrase "fbaudiencenetwork 6.14.0 podspec"
5. Open a search result: https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.14.0/FBAudienceNetwork.podspec.json
6. Notice the final part of the path from it: ../Specs/2/1/5/FBAudienceNetwork/6.14.0/FBAudienceNetwork.podspec.json
7. Switch on hidden files visibility by pressing: Command + Shift + "." on your Mac
8. Open a file on your machine: /Users/YOURUSERNAME/.cocoapods/repos/trunk/Specs/2/1/5/FBAudienceNetwork/6.14.0
9. Edit the line with source location to: "source": {
    "http": "https://YOURDOMAINNAME.games/FBAudienceNetwork-6.14.0.zip",
10. Switch off hidden files visibility by pressing Command + Shift + "."  again
11. Now your can build your game from Unity and all pods will be loaded fine!

**Comment by abeeriqbal** [comment]
Issue is resolved using VPN. After using VPN pod install issue fixed
