### ISSUE TITLE
FBSDKLog: starting with Graph API v2.4, GET requests for /{appId}/model_asset should contain an explicit "fields" parameter

### ISSUE THREAD

**Issue by adamrushy** [facebook/facebook-ios-sdk#1403]
## Checklist

- [ ✅] I've updated to the latest released version of the SDK
- [ ✅] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [ ✅] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [ ✅] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [ ✅] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.4.1`
- Swift Version: `5` (if issue is Swift related)
- Installation Platform & Verison: `[Cocoapods]` version `1.8.4`

## Goals

I have the FBSDKCoreKit installed and running a simple `activateApp`.

## Expected Results

I expect the installation to run correctly and start receiving app events.

## Actual Results

I get an HTTP Error and receive this in the logs;

FBSDKLog: starting with Graph API v2.4, GET requests for /{appId}/model_asset should contain an explicit "fields" parameter

## Steps to Reproduce

1. Run the app
2. Check the logs

## Code Samples & Details

I don't actually have any custom code here. I import the module and then run the below code;

```swift
        if let facebookAppId = SbAppDefaults.shared()?.value(forKey: kSbFacebookAppId) as? String {
            Settings.appID = facebookAppId
            AppEvents.activateApp()
        }
```

The issue looks to be inside the framework and class FBSDKModelManager.m 

```objective-c
    // fetch api
    FBSDKGraphRequest *request = [[FBSDKGraphRequest alloc]
                                  initWithGraphPath:[NSString stringWithFormat:@"%@/model_asset", [FBSDKSettings appID]]];
```

If I make a local change to this

```objective-c
FBSDKGraphRequest *request = [[FBSDKGraphRequest alloc] initWithGraphPath:[NSString stringWithFormat:@"%@/model_asset", [FBSDKSettings appID]] parameters:@{@"fields": @""}];
```

That seems to remove this error.

**Comment by poojagupta-simformsolutions** [comment]
Above solution doesn't work for me.

**Comment by joesus** [comment]
This is expected behavior. The latest version of Graph API is 7.0 https://developers.facebook.com/docs/graph-api/

Please update the version of the SDK that you are using. To watch for new releases:
https://docs.github.com/en/enterprise/2.15/user/articles/watching-and-unwatching-repositories

**Comment by sanvean** [comment]
> This is expected behavior. The latest version of Graph API is 7.0 https://developers.facebook.com/docs/graph-api/
> 
> Please update the version of the SDK that you are using. To watch for new releases:
> https://docs.github.com/en/enterprise/2.15/user/articles/watching-and-unwatching-repositories

I think this issue needs re-opening, getting exactly the same warning with SDK Version 7.1.1. I guess an old Graph API call must be buried somewhere? I investigated this after our app received a Graph API upgrade warning email from Facebook stating 1 call was still using an old Graph API call. This appears to be it:

FBSDKLog: starting with Graph API v2.4, GET requests for /{app_id}/model_asset should contain an explicit "fields" parameter

Xcode 11.5
Swift Version: 5.2.4
SDK Version: 7.1.1 (Installed via SPM in Xcode)

Note for GDPR compliance the FB SDK in our app is only initialised after the user provides consent. This warning above is received on launch before we even initialise the SDK with:

`Settings.isAutoInitEnabled = true`
`ApplicationDelegate.initializeSDK(nil)`

**Comment by sanvean** [comment]
Additionally looking at the warning email from FB. Will the SDK still work post **July 28th**? Or is the SDK going to fail to initialise?

_Your App, XXX, is currently accessing Graph API v3.0 which will reach the end of its 2-year lifetime on **28 July, 2020**. We estimate 1 endpoint that XXX calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v3.1 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.

Visit our changelog to see the full list of changes in all Graph API versions._

**Comment by joesus** [comment]
@sanvean as the email stated. One endpoint will stop working. I don't know the version you are using so I cannot speak to its behavior. Is there a reason to avoid upgrading to a newer version?

**Comment by sanvean** [comment]
Hi @joesus I'm using what I believe is the latest official version - 7.1.1 installed via SPM in Xcode. Is it something to do with not auto-initialising the SDK until post-launch (for GDPR compliance)?

**Comment by kevinjameshunt** [comment]
I'm seeing the same thing with FBSDKCoreKit 7.1.1 as well. We also initialize the SDK post-launch after consent checks are complete. The SDK is hitting the the /v7.0 graph endpoint and receiving a 400 error from a GET request like:

https://graph.facebook.com/v7.0?fields=app_events_feature_bitmask%2Cname%2Cdefault_share_mode%2Cios_dialog_configs%2Cios_sdk_dialog_flows.os_version%2814.0.0%29%2Cios_sdk_error_categories%2Csupports_implicit_sdk_logging%2Cgdpv4_nux_enabled%2Cgdpv4_nux_content%2Capp_events_session_timeout%2Clogging_token%2Crestrictive_data_filter_params%2Caam_rules%2Csuggested_events_setting%2Cauto_event_mapping_ios%2Csdk_update_message&format=json&include_headers=false&sdk=ios

**Comment by sanvean** [comment]
This appears to be fixed as of v8.0.0...

**Comment by kevinjameshunt** [comment]
Sadly not, I still see the same error for v8. 

<img width="1374" alt="Screen Shot 2020-10-01 at 10 34 36 AM" src="https://user-images.githubusercontent.com/1033531/94833318-fdc27480-03dc-11eb-92db-d608e24e9fa0.png">

**Comment by joesus** [comment]
Fixed for next release.

**Comment by Idomo** [comment]
@joesus Still getting this log message with version `11.2.1`.

**Comment by RizITN10** [comment]
Same is the case in 17.0.0

**Comment by xsgoing** [comment]
Same is the case in 17.0.1

**Comment by DataGreed** [comment]
Whyy was it closed? Same warning on 17.4
