### ISSUE TITLE
App Events not reaching Facebook / SKAdNetwork attribution problems

### ISSUE THREAD

**Issue by danmaas** [facebook/facebook-ios-sdk#1667]
(this is a follow-up to consolidate the main questions from #1632 and #1639)

To summarize, despite trying very hard to follow all the best practices around iOS 14 App Events and install attribution, we are still failing to get events to appear in Facebook's App Events Insights panel, and failing to attribute installs to iOS 14 campaigns in Ads Manager. We are not sure if this is a code bug, or incorrect interpretation of the documentation, or maybe an issue with Facebook's internal data systems rather than the iOS SDK.

## Checklist

- [x] I've updated to the latest released version of the SDK (Yes, SDK `9.0.1`)
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues) (this continues discussion after  #1632 was closed, since the issue is not fixed)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.4`
- Swift Version: N/A
- Installation Platform & Verison: `Cocoapods` version `1.10.0`

## Goals/Expected Results

1. The Facebook SDK remains dormant until we receive user consent to send data, after which:
2. App Events appear in our Facebook App's Events insights panel, including both automatically-logged events like App Install plus manually-logged events from `[FBSDKAppEvents logEvent]`.
3. iOS 14 ad campaigns in Ads Manager show plausible App Install numbers, after waiting the proper 3 days for SKAdNetwork attribution to occur.

Note: at no point is the user signing in with a Facebook account, nor do we want to touch the IDFA at all. We only want to send what is possible without an active login session and without asking for IDFA.

(Actually, I'm afraid the docs are not very clear about whether this is even possible: can we send log events to Facebook without first asking the user to sign in, or querying the IDFA? It would be nice to clarify what data can be logged, if any, without these steps.)

## Actual Results

All App Events do appear in the iOS device log, when enabled via `[FBSDKSettings enableLoggingBehavior:FBSDKLoggingBehaviorAppEvents];`. This includes both automatically-logged and manually-logged events.

However, we do NOT see any events in the Events Manager Test Events panel (https://business.facebook.com/events_manager2/list/app/APPID/test_events), nor the Facebook App Insights panel (https://www.facebook.com/analytics/APPID/AppEvents/), even after 1+ days of waiting.

We can get events to appear in the Test Events panel and App Insights, but only if we do two weird things that seem to contradict the documentation:
1. We set the `_implicitlyLogged` flag to `1` on all events. This is an internal flag that the SDK normally adds only to automatically-logged events. Since automatically-logged events were occasionally appearing on the Test Events panel, we tried adding this flag ourselves, and suddenly all the events started appearing reliably (except App Install - see 2.).
2. We send an App Install event manually by logging a custom event named `fb_mobile_first_app_launch`. Even though we do set `[FBSDKSettings setAutoLogAppEventsEnabled:YES]`, the SDK doesn't seem to be sending its own App Install event.

With the above hacks, I think we are logging app events successfully.

However, we are doubtful that iOS 14 SKAdNetwork attribution is fully working yet, since we see far fewer App Install events in the Ads Manager interface than we would expect, relative to the number of link clicks and typical conversion rates of our campaigns. (based on historical trends, we are pretty confident that our click-to-install conversion rate should be at least 30%, but in Ads Manger we only see about 10% click-to-install on iOS 14 campaigns, which seems abnormally low).

## Steps to Reproduce

Here is how we are interacting with the SDK:

Info.plist, AppDelegate.m:
- all settings made as described in https://developers.facebook.com/docs/ios/getting-started/, plus:
```
	<key>FacebookAdvertiserIDCollectionEnabled</key>
	<false/>
	<key>FacebookAutoInitEnabled</key>
	<false/>
	<key>FacebookAutoLogAppEventsEnabled</key>
	<true/>
```

After receiving user consent to share data (with explicit UI in GDPR countries, otherwise implicitly):

```objc
[FBSDKApplicationDelegate initializeSDK:nil];
[FBSDKSettings setAdvertiserTrackingEnabled:YES];
[FBSDKSettings setAutoLogAppEventsEnabled:YES];
```

i.e., we want to initialize the SDK and then send as much data as we possibly can, except without touching the IDFA.

After making the above 3 calls, I would expect to see events like App Install, App Launch, and our manually-logged events to start appearing in the Events Insights panel. (on Android, using the equivalent SDK calls, they indeed do appear). Also, I would expect that we should start seeing reasonable App Install counts on iOS 14 ad campaigns via SKAdNetwork, after waiting the proper 3-day period for delayed attribution.

**Comment by berseck** [comment]
I'm having same issue.
While testing on 14.5 beta 1 I could make everything work if I had all 3 flags on:

```
setAutoLogAppEventsEnabled:YES
setAdvertiserIDCollectionEnabled:YES
setAdvertiserTrackingEnabled:YES
```

And then initializing the API 

When I started using the Beta 2 nothing works anymore no events, only app_launch

I was expecting based only on the documentation that if I set the auto log events on I would expect to have the app installs and app launch events. But... this is not what is happening.

**Comment by wcleghorn** [comment]
+1 and in addition: 

Looking at the iOS 14.5 requirements put forward by Apple: 

https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track

It would appear (example #4) that an app will be required to receive the user’s permission through the AppTrackingTransparency framework if the Facebook SDK is installed. 

We know that setAdvertiserTrackingEnabled must be enabled in order for an app to send the app_install event automatically. 

https://github.com/facebook/facebook-ios-sdk/blob/v9.0.1/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsUtility.m#L401  

@danmaas can you clarify that your Goals/Expected Results #1 means using ATT? 

It would be nice for clarification around this in Facebook's documentation when installing the SDK.

**Comment by danmaas** [comment]
No, we don't want to touch ATT. The "consent" I was referring to above is more related to GDPR, where we have to get consent even for first-party data storage.

We made a product-level decision not to show the ATT pop-up dialog or use IDFA-based tracking, because it would be perceived very negatively by our user base.

If not using ATT/IDFA means that we cannot log any in-app events, other than SKAdNetwork-based install events, then so be it. But SKAdNetwork attribution seems broken right now and I really hope we can get it working.

My understanding of the Apple and Facebook docs is that it _should_ be possible to get SKAdNetwork to feed App Install events into our iOS 14 ad campaigns, without ATT or IDFA. If I am wrong about this, please let me know!

**Comment by wcleghorn** [comment]
Thanks for the clarification, we are looking for the same thing. I'll let you know if I find anymore details or confirmation on anything.

**Comment by danmaas** [comment]
An update on SKAdNetwork - we are starting to think that the SKAdNetwork App Install counts are actually correct, and it's just that our Facebook iOS 14 campaigns are doing a poor job of targeting users who will install our app after clicking on the ad.

We usually see click-to-install conversion rates of 30-40% on other types of campaigns, but the new iOS 14 campaigns are only delivering 5-10% click-to-install rates.

The above results are from about $1,000 in ad spend on iOS 14 campaigns. Is that just too little to teach the FB algorithms to find good users? We hesitate to throw more money at this without knowing whether it is likely to improve things XD.

**Comment by JustinGanzer** [comment]
Experiencing the same "issue". We've increased spending for iOS 14 campaigns but the click to install conversion is terrible when compared to earlier campaigns at something like 4% or less.
Android and Pre iOS14 campaigns with the same content did hugely better.

**Comment by danmaas** [comment]
@nutlike Here is the patch we use to force the _implicitlyLogged flag to 1 on all events, by adding it inside `logEvent()` and `logPurchase()`:

```
diff --git a/node_modules/react-native-fbsdk/src/FBAppEventsLogger.js b/node_modules/react-native-fbsdk/src/FBAppEventsLogger.js
index 25a99de..658f461 100644
--- a/node_modules/react-native-fbsdk/src/FBAppEventsLogger.js
+++ b/node_modules/react-native-fbsdk/src/FBAppEventsLogger.js
@@ -83,6 +83,11 @@ module.exports = {
     let parameters = null;
     if (typeof args[0] === 'object') {
       parameters = args[0];
+    } else {
+      parameters = {};
+    }
+    if(true) { // DJM - the SDK doesn't seem to get events through to Facebook unless this flag is set
+      parameters['_implicitlyLogged'] = '1';
     }
     AppEventsLogger.logEvent(eventName, valueToSum, parameters);
   },
@@ -95,6 +100,10 @@ module.exports = {
     currencyCode: string,
     parameters?: ?Params,
   ) {
+    if(!parameters) { parameters = {}; }
+    if(true) { // DJM - the SDK doesn't seem to get events through to Facebook unless this flag is set
+      parameters['_implicitlyLogged'] = '1';
+    }
     AppEventsLogger.logPurchase(purchaseAmount, currencyCode, parameters);
   },
 
```

Note, due to the lack of feedback on this issue of missing conversion events, and the poor performance of our test iOS 14 ad campaigns, we have stopped advertising on Facebook for now. We shifted our resources to better-performing sources, like iOS App Store campaigns.

**Comment by arodriguezju** [comment]
@danmaas Do I understand correctly, that if one just needs SKAdNetwork data there is no need of setting any SDK flag? Thanks!

**Comment by danmaas** [comment]
I *think* SKAdNetwork install events (if not purchase events) will come through automatically, without manually setting the `_implicitlyLogged` flag. I'm not 100% sure through.

**Comment by kesha-antonov** [comment]
Same issue

**Comment by SonChanthem** [comment]
Hello @danmaas ,
I also have the same issue here. I've follow you suggestion. But the events don't log at all even Standard and Custom Events. 
I've test on device iPhoneX OS 14.1. 

+ FB SDK latest version v11.0

* Noted: I've tried to test on device below iOS 14, the event was record in Analytic and Events Manager.

Anything more suggestion for this? 

I'm really appreciate of your shared.

Thank you

**Comment by angelchavez2** [comment]
`source`

**Comment by angelchavez2** [comment]
> exit

**Comment by tgioihan** [comment]
Same with me, anyone knows how to resolve it ?

**Comment by saagarvaru** [comment]
I am also facing this issue. I have tried everything under the sun to get event to log and nothing is showing up in the events test page

**Comment by jonathanroze** [comment]
Same issue, I tried on many versions of Facebook SDK and it's always the same result.. no events

**Comment by rahulsmehta** [comment]
Bigger picture, we're noticing that only Mobile App Install events are showing in the Ads Manager (both using the FB SDK as well as Adjust after we switched to using an MMP). Also CPMs have gone up across the board, but that seems to be a bigger problem overall due to the iOS 14 rollout

**Comment by VictorIkonnikov** [comment]
I have the same issue. The documentation says to disable this in .plist and call after initialization but it doesn't work

FBSDKSettings.setAutoLogAppEventsEnabled(true)
FBSDKSettings.setAdvertiserIDCollectionEnabled(true);

but for both Xcode says "Type has no member 'setAutoLogAppEventsEnabled'"

**Comment by Fublvckmagik** [comment]
Did someone solve the problem with IOS 14+ ?

**Comment by uniqby** [comment]
Same issue, I tried on many versions of Facebook SDK and it's always the same result.. no events

**Comment by Fublvckmagik** [comment]
I am using AppSlyer and did a Facebook integration.
With AppsFlyer I started getting all the events!

**Comment by KylinChang** [comment]
Hi @danmaas , 

1. starting from iOS 14.5 and above, the flag for AdvertiserTrackingEnabled is false by default and you will need to call `setAdvertiserTrackingEnabled:YES` to send the app events and you don't need to set `_implicitlyLogged` flag. If you cannot see the app events after you call `setAdvertiserTrackingEnabled:YES`, can you double check you logged in FB App on the same device?
2. For SKAN attribution, we will attribute events to the install even if you don't call `setAdvertiserTrackingEnabled:YES`.

**Comment by Fublvckmagik** [comment]
@KylinChang Hello, o have this code for initializing FBSDK in AppDelegate:

        ApplicationDelegate.shared.application(application,didFinishLaunchingWithOptions: launchOptions)
        Settings.setAdvertiserTrackingEnabled(true)
        Settings.isAdvertiserIDCollectionEnabled = true

After this code, in controller I call Event method :
       AppEvents.logEvent(.purchased)
       
What am I doing wrong?

**Comment by KylinChang** [comment]
Hi @Fublvckmagik , What's the issue you are having now, App Events not showing up in "Test Events" or SKAN install number issue? It seems that you don't call the method `initializeSDK` , you will need to explicitly call `initializeSDK` after v9.0.0 .

**Comment by revolter** [comment]
The `initializeSDK` method was removed.

**Comment by Fublvckmagik** [comment]
> Hi @Fublvckmagik , What's the issue you are having now, App Events not showing up in "Test Events" or SKAN install number issue? It seems that you don't call the method `initializeSDK` , you will need to explicitly call `initializeSDK` after v9.0.0 .

In Facebook documentation says that initialization happens here:
`ApplicationDelegate.shared.application(application,didFinishLaunchingWithOptions: launchOptions)`

Also I dint find "initializeSDK" method, just `ApplicationDelegate.initialize()`

**Comment by PrimulaX** [comment]
Same.
It logs nothing on facebook's events test page.

**Comment by Fublvckmagik** [comment]
> Same.
> It logs nothing on facebook's events test page.

Don't check test page, check on Dashboard [(image link)](https://ibb.co/yBc0hzd)

**Comment by PrimulaX** [comment]
@Fublvckmagik I haven't released app yet, there are lots of activity tho, how can I distinguish them.

**Comment by KylinChang** [comment]
> The `initializeSDK` method was removed.

Hi @revolter , you may need to call `application:didFinishLaunchingWithOptions:` of FBSDKApplicationDelegate to initialize the SDK in the latest SDK.

**Comment by KylinChang** [comment]
> Same.
> It logs nothing on facebook's events test page.

Hi @PrimulaX , Can you please double check followings:
1. The event is sent successfully. You can set `FBSDKSettings`'s loggingBehaviors as a set of `FBSDKLoggingBehaviorAppEvents, FBSDKLoggingBehaviorNetworkRequests` to check the log
2. IDFA is attached to the events in your app
3. You logged in FB App on the same device and you opt-in in FB App

**Comment by PrimulaX** [comment]
@kalgynirae I'm using iOS SDK wrapper for react-native but I believe I'm doing these things.

**Comment by KylinChang** [comment]
> @kalgynirae I'm using iOS SDK wrapper for react-native but I believe I'm doing these things.

Thanks for the info. Are you using this library https://github.com/facebookarchive/react-native-fbsdk ?

**Comment by PrimulaX** [comment]
> Thanks for the info. Are you using this library https://github.com/facebookarchive/react-native-fbsdk ?
I'm using community one, react-native-fbsdk-next.

**Comment by tereshchenkoartyom94-da** [comment]
The same issue. Tried all the solutions above.
Can it be caused by my simulator? I don't have a real iPhone device

**Comment by victoriaSh** [comment]
Similar issue.
I have the app for kids (com.cosmopanda.videoalphabet, if it helps) and don't want to use IDFA or pop-up windows.
I use react-native-fbsdk-next and FBSDKCoreKit version is 9.3.0.
What I've done:
- All needed settings from react-native-fbsdk-next 
- Enabled SKAdNetwork in Events Manager
- Steps 3 and 4 from  https://developers.facebook.com/docs/ios/use-cocoapods (there is typo in docs - steps 4 and 4)
- Changed my AppDelegate. There is a mix from react-native-fbsdk-next docs and facebook docs ( I can't find the page I've used)
```
#import <FBSDKCoreKit/FBSDKCoreKit.h>
...
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url
            sourceApplication:(NSString *)sourceApplication
            annotation:(id)annotation
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    //if (![RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    //}
    if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
      return YES;
    }

    if ([RCTLinkingManager application:app openURL:url options:options]) {
      return YES;
    }
  //return YES;
    return [[FBSDKApplicationDelegate sharedInstance] application:app
                                                           openURL:url
                                                 sourceApplication:sourceApplication
                                                        annotation:annotation];
}

```
- After initial app mount I call 
```
FBSettings.initializeSDK();
AppEventsLogger.logEvent('test', 14, { type: 'ios' });
```
There is no any logs or errors about fbsdk.
I have also installed Branch to track SKAdNetwork installs. 
There is no any events and installs in Events Managers and Branch.

Am I missing something?
How fast do events and installs appear? I'm trying to build with different settings for 4 days.
How to test SKAdNetwork installs correctly?

I will be very glad for any help.

**Comment by PrimulaX** [comment]
@victoriaSh I have done same the things and while on the test page in Event Manager logs coming from only devices with below 14 iOS versions.

**Comment by KylinChang** [comment]
Hi @PrimulaX , did you call `setAdvertiserTrackingEnabled:YES` in your app?

**Comment by KylinChang** [comment]
> The same issue. Tried all the solutions above.
> Can it be caused by my simulator? I don't have a real iPhone device

I don't think it's caused by the simulator

**Comment by KylinChang** [comment]
> Similar issue.
> I have the app for kids (com.cosmopanda.videoalphabet, if it helps) and don't want to use IDFA or pop-up windows.
> I use react-native-fbsdk-next and FBSDKCoreKit version is 9.3.0.
> What I've done:
> 
> * All needed settings from react-native-fbsdk-next
> * Enabled SKAdNetwork in Events Manager
> * Steps 3 and 4 from  https://developers.facebook.com/docs/ios/use-cocoapods (there is typo in docs - steps 4 and 4)
> * Changed my AppDelegate. There is a mix from react-native-fbsdk-next docs and facebook docs ( I can't find the page I've used)
> 
> ```
> #import <FBSDKCoreKit/FBSDKCoreKit.h>
> ...
> - (void)applicationDidBecomeActive:(UIApplication *)application {
>   [FBSDKAppEvents activateApp];
> }
> 
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url
>             sourceApplication:(NSString *)sourceApplication
>             annotation:(id)annotation
>             options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
>     //if (![RNBranch application:app openURL:url options:options])  {
>         // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
>     //}
>     if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
>       return YES;
>     }
> 
>     if ([RCTLinkingManager application:app openURL:url options:options]) {
>       return YES;
>     }
>   //return YES;
>     return [[FBSDKApplicationDelegate sharedInstance] application:app
>                                                            openURL:url
>                                                  sourceApplication:sourceApplication
>                                                         annotation:annotation];
> }
> ```
> 
> * After initial app mount I call
> 
> ```
> FBSettings.initializeSDK();
> AppEventsLogger.logEvent('test', 14, { type: 'ios' });
> ```
> 
> There is no any logs or errors about fbsdk.
> I have also installed Branch to track SKAdNetwork installs.
> There is no any events and installs in Events Managers and Branch.
> 
> Am I missing something?
> How fast do events and installs appear? I'm trying to build with different settings for 4 days.
> How to test SKAdNetwork installs correctly?
> 
> I will be very glad for any help.

Hi @victoriaSh , I noticed that you didn't call `setAdvertiserTrackingEnabled:YES`. Starting from iOS 14.5, the default value for AdvertiserTrackingEnabled flag is false and we will drop events if the flag is false. If you want to test with "Test Events" in Events Manager, you will need IDFA attached with your events and need to log in FB App on the same device. For SKAN, it may take 2 to 3 days for SKAN install to appear and it'd be better if you could provide your FB App ID to my email so I can investigate further.

**Comment by guerri-17** [comment]
I am using FBSDKCoreKit 11.0.1, Xcode 12.5.1, Swift 5.x. I would like to track standard or custom events only, no ad for installation for now. I have added the POD to an existing prod app (now being tested) and a new basic Swift app(with AppID).  I have the SDK initialization in AppDelegate and in SceneDelegate.swift.  However, as others have reported, I am not seeing any AppEvents.logEvent(.viewedContent) listed from either app in the Test Events of Events Manager.  How else may I troubleshoot?  Thank you.

**Comment by PrimulaX** [comment]
@KylinChang yes I did.

here is my code: 

```
const ATT_CHECK = await check(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);

        if (ATT_CHECK === RESULTS.DENIED) {
            try {
                const ATT = await request(PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY);
                if (ATT === RESULTS.GRANTED) {
                    Settings.setAdvertiserTrackingEnabled(true);
                }
            } catch (error) {
                throw error;
            } finally {
                Settings.initializeSDK();
            }
```

**Comment by guerri-17** [comment]
I found this API - https://developers.facebook.com/docs/marketing-api/app-event-api/. In section "App Installs", I submitted in macOS terminal, this curl call - curl -i -X POST "https://graph.facebook.com/{app-id}/activities
   ?event=MOBILE_APP_INSTALL
   &application_tracking_enabled=0      
   &advertiser_tracking_enabled=0       
   &advertiser_id={advertiser-tracking-id}
   &{app-access-token}" but without the app-access-token and got "success" as a JSON response.  However, I don't see it listed as an Event in Facebook.com/events_manager2 for my test app.  I am not sure how to construct this call in Swift.  

When I try to use the Manually Log Events "Get Code" of https://developers.facebook.com/docs/app-events/getting-started-app-events-ios, I get no response clicking on the "Get Code" button in Safari, Chrome, or Firefox.  Does it only work on Windows?  Thank you.

**Comment by AWONGWY10** [comment]
I'm having the same issue as well. Tried all the above doesn't works.
And still showing app is out of date, ask to update to latest Facebook SDK which I already did (SDK 11.0.1.) and waited for 1 week the message still there.

**Comment by dhayaljaswantgit** [comment]
I've almost tried everything but not able to log Events on iOS however Android same code working fine, no build error, successfully able to run.

Here is my code => 

<pre>
import {AppEventsLogger, Settings} from 'react-native-fbsdk-next';

export const facebookSDKInit = async () => {
  const trackingStatus = await requestTrackingPermission();
  if (Platform.OS === 'ios' && parseInt(Platform.Version) > 13) {
    if (trackingStatus === 'authorized') {
      await Settings.setAdvertiserTrackingEnabled(true);
    }
  }
  Settings.initializeSDK();
};
</pre>

I'm calling this in App.js file on component mount and it's asking me for permission 

<pre>
import {AppEventsLogger, Settings} from 'react-native-fbsdk-next';
AppEventsLogger.logEvent('login',{user : 'user', email : 'email'});
</pre>

On Android everything working fine

Someone can help me here

Thanks in Advance

**Comment by guerri-17** [comment]
For those who have been successful in seeing their Events in Events Manager, would you mind listing where you see them - is it in https://www.facebook.com/eventmanager2 where we test our apps with Facebook SDK included?  

What event works for you - Custom Event or Standard Event?

What parameters do you need to include - does it only work if you use Facebook login -> do you need to include app-access-token? Do you need to include advertiser_tracking_id ?

Has anyone tried the curl call above using app-event-api and does your event show up in "Test Events" of https://www.facebook.com/eventmanager2?  

Would you mind providing your Swift code for "AppEvents.logEvent()" if you were successful?

Thank you all.

**Comment by varun-s** [comment]
@KylinChang The only way i can get events to show up is by setting  `Settings.isAdvertiserIDCollectionEnabled = true`
(in test panel for now as we released the app without this setting and not receiving any events). 

Why is that? We do not want to to show the ATT prompt in order to get user consent and don't want to send the IDFA.

Setup that works:
`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`
` Settings.isAutoLogAppEventsEnabled = true`
`Settings.setAdvertiserTrackingEnabled(true)`
`Settings.isAdvertiserIDCollectionEnabled = true` <----

Setup that does not work:
`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`
` Settings.isAutoLogAppEventsEnabled = true`
`Settings.setAdvertiserTrackingEnabled(true)`
`Settings.isAdvertiserIDCollectionEnabled = false` <---

Please advice
Thank you

**Comment by varun-s** [comment]
Got it to finally work by updating the FacebookClientToken in info.plist.
Weird, cause the documentation a few days ago said to replace CLIENT_TOKEN placeholder with the app name?!
In the latest documentation it says to replace with client token found in the app dashboard.
`https://developers.facebook.com/docs/app-events/getting-started-app-events-ios`

Current settings
`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`
`Settings.isAutoLogAppEventsEnabled = true`
`Settings.setAdvertiserTrackingEnabled(true)`
`Settings.isAdvertiserIDCollectionEnabled = false`

`<key>FacebookAdvertiserIDCollectionEnabled</key>`
`<false/>`
`<key>FacebookAppID</key>`
`<string>....</string>`
`<key>FacebookAutoLogAppEventsEnabled</key>`
`<true/>`
`<key>FacebookClientToken</key>`
`<string>[CLIENT-TOKEN]</string>` <---- `from https://developers.facebook.com/apps/[YOUR-APP-ID]/settings/advanced/`
`<key>FacebookDisplayName</key>`
`<string>.....</string>`

**Comment by guerri-17** [comment]
Hi Varun,

Your pointer on CLIENT_TOKEN is most helpful.  I'm now getting better FBSKLog comments but am still not seeing event in https://www.facebook.com/eventmanager2.

Do you need to test on a physical device and not through Xcode simulator?

Are you not including the advertiser_id (Ad Account ID) and it works for you?

Thank you.

**Comment by SonChanthem** [comment]
Hi @varun-s,

**Comment by varun-s** [comment]
@guerri-17 : I tested on a physical device. I don't think it works on the simulator (As instructions indicate that you need to be logged-in to the Facebook app too).
My objective is to get app_install/automatic events so i do not need to include an advertiser_id.

 @SonChanthem : I need to release another build to the app store with the new settings (Which includes the client token). 
 I was able to get events to show up in the test panel only at the moment. Will keep you posted post release.
The warning is by design.. You can ignore it if you are not planning to to get user consent  via ATT prompt / use IDFA.

**Comment by SonChanthem** [comment]
@varun-s, I've set up implement like below. But I still didn't get any events showing in test panel even standard event such app_install that is automatic record by SDK.
I'm testing on real device iPhone X, iOS 14.6 and I had allow ATT prompt.

Implementation in AppDelegate method. 
ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
Settings.isAutoLogAppEventsEnabled = true
Settings.isAdvertiserIDCollectionEnabled = true
ATTrackingManager.requestTrackingAuthorization { (status) in
   if status == .authorized {
      Settings.setAdvertiserTrackingEnabled(true)
   }
}

**My info.plist file**
<key>FacebookAdvertiserIDCollectionEnabled</key>
<true/>
<key>FacebookAppID</key>
<string>$(FB_APP_ID)</string>
<key>FacebookAutoLogAppEventsEnabled</key>
<true/>
<key>FacebookClientToken</key>
<string>$(FB_CLIENT_TOKEN)</string>
<key>FacebookDisplayName</key>
<string>$(FB_DISPLAY_NAME)</string>

Is your side have implement ATT prompt? As document mentioned it need to iOS 14.5.
https://developers.facebook.com/docs/app-events/getting-started-app-events-ios/#get-device-consent

**Comment by varun-s** [comment]
@SonChanthem No, we are not using the ATT prompt. Are you logged-in to the Facebook app on the same device?

**Comment by guerri-17** [comment]
@SonChanthem, @varun-s:

Thank you both - I finally have some test events working. I agree with Varun, this iOS SDK requires Facebook app to be running concurrently as your app on a physical device, in order for the Api requests to get to Facebook for logging.

I also have "ApplicationDelegate.initialize() return true" at the end of "func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {" in AppDelegate.swift.

I will test whether it is needed or not.  I do not use ATT prompt and I created a Custom event (stackoverflow help):

let eventName: AppEvents.Name = AppEvents.Name(rawValue: "RequestMentor")
AppEvents.logEvent(eventName)
AppEvents.flush()   //will test if this is needed or not

Attached is my Test Screen which shows up in both Facebook.com/events_manager2 and business.facebook.com/events_manager2:

<img width="827" alt="Screen Shot 2021-07-19 at 8 16 19 PM" src="https://user-images.githubusercontent.com/26355211/126245272-25956814-b5b4-4380-b716-1eba0c1c1b6e.png">

**Comment by tereshchenkoartyom94-da** [comment]
OMG, I made it.
The problem was in Facebook App
YOU HAVE TO BE LOGGED IN FACEBOOK APP and use a real device

otherwise, SDK will not work

**Comment by DomRiedweg** [comment]
@varun-s Thank you for update about the client id, I also used the app name (according to the documentation at that time). 

Anyway I'll fix that but before I waste another 3 days waiting for events, maybe someone can confirm if my settings should work (@KylinChang maybe, thank you).

Goal: No tracking except SKAN so I don't expect to see any events in event_manager2. 

Version: 9.0.3

Initialise, it's not clear which method I need to call:
        ApplicationDelegate.initialize()
        Settings.initialize()

        Settings.setAdvertiserTrackingEnabled(false)
        Settings.isAutoLogAppEventsEnabled = true
        Settings.isAdvertiserIDCollectionEnabled = false

ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions) is implemented in SceneDelegate.

Is my understanding correct that this should give me app_install through SKAN only?


Or can I also switch off AutoLogAppEvents and call SKAdNetwok manually, it’s only 2 different methods anyway
    SKAdNetwork.registerAppForAdNetworkAttribution()
    SKAdNetwork.updateConversionValue(1)

But I couldn’t find how optimise for my custom conversionValue in even_manager2 (the higher the better).

**Comment by SonChanthem** [comment]
@varun-s: Yes I do. My device had Facebook App and I also logged in Facebook account. One more thing as you mention, you didn't request ATT prompt. So What's the value do you set for this method `Settings.setAdvertiserTrackingEnabled(false) or Settings.setAdvertiserTrackingEnabled(true)`?. And did you testing from iOS 14?

How about these 2 methods?
```
ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
ApplicationDelegate.initialize()
```
Did you call both ? Which one is called first ? May you help the share the code in `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool` ? 

@guerri-17 : As your testing are working , Could you shared how do you set all these option both in plist file and in AppDelegate?

```
Settings.setAdvertiserTrackingEnabled(Boolean)
Settings.isAutoLogAppEventsEnabled = Boolean
Settings.isAdvertiserIDCollectionEnabled = Boolean
```

By the way, I'm not sure is it correct or not. but I requested ATT prompt base on this document mentioned that it need to set this flag True for iOS 14.5 up. 
https://web.facebook.com/business/help/2750680505215705?id=428636648170202&_rdc=1&_rdr
<img width="626" alt="Screen Shot 2021-07-21 at 10 34 10 AM" src="https://user-images.githubusercontent.com/19567034/126427231-90a38c95-cbb0-41c5-96b7-bff1aff205b0.png">

**Comment by julien-tamade** [comment]
Also running into this issue of events not reaching the events manager. I'm using SDK version 11.0.1. I tried changing my setup to this:

`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`
then I request Tracking permission

```
func requestTracking(){
        if #available(iOS 14, *) {
            AppsFlyerLib.shared().waitForATTUserAuthorization(timeoutInterval: 40)
            ATTrackingManager.requestTrackingAuthorization(completionHandler: { (status) in
                switch status{
                case .authorized:
                    Settings.setAdvertiserTrackingEnabled(true)
                    break
                case .denied:
                    Settings.setAdvertiserTrackingEnabled(false)
                default:
                    break
                }
                print("AppDelegate: permission decided \(status.rawValue)")
                self.initializeFBSDK()
            })
        }else{
            self.initializeFBSDK()
        }
    }
```

and finally initialize the sdk
```
func initializeFBSDK(){
        Settings.isAutoLogAppEventsEnabled = true
        Settings.isAdvertiserIDCollectionEnabled = true
        ApplicationDelegate.initialize()
    }
```

Still not receiving the events in events manager. Anybody have a definitive setup that works? The Facebook Documentation is really bad so I'm just swimming in the dark here? is ApplicationDelegate.initialize() required? is that supposed to be called before or after everything else? @DomRiedweg asked if Settings.initialize() needs to be called and I echo that? Anybody know what's gonna work?

**Comment by tereshchenkoartyom94-da** [comment]
@julien-tamade I made events work, but my commend has many dislikes

Dou have a Facebook app installed?

**Comment by julien-tamade** [comment]
@tereshchenkoartyom94-da yes I have the app and am logged in. Could you share how you're initializing the SDK? and is it working on iOS 14.6?

**Comment by guerri-17** [comment]
@SonChanthem - I'm curious if you have actual aliases set up or they are just placeholders in lieu of your actual values for this forum thread - "$(FB_APP_ID)".  One thing to double check is the URL Scheme - 
<key>CFBundleURLTypes</key>
<array>
  <dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fbAPP-ID</string> // **fb** is part of the ID to distinguish this Facebook identifier from others
  </array>
  </dict>
</array>

To troubleshoot, I would recommend starting simple - set your info.plist to have AutoLog, setAdvertiserTracking, and AdvertiserIDCollection enabled.  Comment out your checking logic for iOS 14 ATT for now.

I would have "ApplicationDelegate.initialize() return true" after "ApplicationDelegate.shared.application(
               application,
               didFinishLaunchingWithOptions: launchOptions
           )", 

which is at end of 
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool 

Pick a screen that upon viewDidLoad() would call:

AppEvents.logEvent(.viewedContent)  //try standard Event
AppEvents.flush()

I would also check that your graph API call (behind the scene request from logEvent) works from your Terminal:

curl -i -X POST "https://graph.facebook.com/{app-id}/activities
   ?event=MOBILE_APP_INSTALL
   &application_tracking_enabled=0      
   &advertiser_tracking_enabled=0       
   &advertiser_id={advertiser-tracking-id}

Adjust parameters accordingly to get "success" as a response.  It is just checking if your app-id and tracking-id values are valid.

This is the Swift process I went through to reduce the # of variables involved and to account for the different components of this iOS SDK workflow.  Hope it helps.

**Comment by julien-tamade** [comment]
Tip for anybody not getting test events in events manager even while being logged in to facebook app: Make sure you have tracking enabled on the Facebook app too. My tracking for facebook app was turned off but once i turned it on i started to get the events.

**Comment by ryan-so** [comment]
@julien-tamade thanks this worked for me. Finally seeing data on Test Events!

**Comment by KylinChang** [comment]
Close the task as it's not a bug of FB SDK.

**Comment by SonChanthem** [comment]
> @SonChanthem - I'm curious if you have actual aliases set up or they are just placeholders in lieu of your actual values for this forum thread - "$(FB_APP_ID)". One thing to double check is the URL Scheme -
> CFBundleURLTypes
> 
> 
> CFBundleURLSchemes
> 
> fbAPP-ID // **fb** is part of the ID to distinguish this Facebook identifier from others
> 
> 
> 
> To troubleshoot, I would recommend starting simple - set your info.plist to have AutoLog, setAdvertiserTracking, and AdvertiserIDCollection enabled. Comment out your checking logic for iOS 14 ATT for now.
> 
> I would have "ApplicationDelegate.initialize() return true" after "ApplicationDelegate.shared.application(
> application,
> didFinishLaunchingWithOptions: launchOptions
> )",
> 
> which is at end of
> func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool
> 
> Pick a screen that upon viewDidLoad() would call:
> 
> AppEvents.logEvent(.viewedContent) //try standard Event
> AppEvents.flush()
> 
> I would also check that your graph API call (behind the scene request from logEvent) works from your Terminal:
> 
> curl -i -X POST "[https://graph.facebook.com/{app-id}/activities](https://graph.facebook.com/%7Bapp-id%7D/activities)
> ?event=MOBILE_APP_INSTALL
> &application_tracking_enabled=0
> &advertiser_tracking_enabled=0
> &advertiser_id={advertiser-tracking-id}
> 
> Adjust parameters accordingly to get "success" as a response. It is just checking if your app-id and tracking-id values are valid.
> 
> This is the Swift process I went through to reduce the # of variables involved and to account for the different components of this iOS SDK workflow. Hope it helps.

Hi @guerri-17 ,

For FB_APP_ID I've set actual value. This "$(FB_APP_ID)" is just my placeholder and ```
URL Scheme -
> CFBundleURLTypes
``` also set correct value. 

In info.plist file I had set FacebookAutoLogAppEventsEnabled with True value. 
In func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool add the following code without request to ATT prompt anymore

```
ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
Settings.isAutoLogAppEventsEnabled = true
Settings.setAdvertiserTrackingEnabled(true)
Settings.isAdvertiserIDCollectionEnabled = false
ApplicationDelegate.initialize()
```

I used this setting to enable console log `Settings.enableLoggingBehavior(.networkRequests)`. The response in console is success with code 200
```
Response Body:
(
        {
        body =         {
            success = 1;
        };
        code = 200;
    }
)

```

**Comment by guerri-17** [comment]
@SonChanthem - Hi, KylinChang has closed this thread. To be transparent, my events are showing up in the Overview tab and not in the Test Events tab.  May be because we have only 1 prod app with 1 prod Apple App ID.  
If you have AutoLog, AdvertiserTracking, and AdvertiserCollectionID set to True in info.plist, you don't need to set them in AppDelegate.swift.  If you are using ATT prompt, then you would need to override these values based on user's response.

But for debugging, just use your settings from info.plist.  I have AdvertiserIDCollection on, because I need to work on SKAN next.  I don't know if it can be off for Event Tracking.  Rather relying on auto events tracking, do you have a screen that upon viewDidLoad calls on AppEvents.logEvent(.viewedContent), a standard event?

Did you try the curl call?  I also see this in the overview tab:
<img width="283" alt="Screen Shot 2021-07-22 at 11 26 19 PM" src="https://user-images.githubusercontent.com/26355211/126734327-8792e2f5-6da6-440d-87fa-ef388197fb04.png">

Not sure what else I can share.

**Comment by grashupfer99** [comment]
I do firmly confirm that I can see live events in **Test Events** and later in **Overview**.

I’m using the following configuration: 

In **AppDelegate.swift** inside **func application** before `return true`

```swift
	// init FBSDK
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)

       // Logging Behavior
        Settings.enableLoggingBehavior(.appEvents)
        Settings.enableLoggingBehavior(.networkRequests)
        Settings.enableLoggingBehavior(.developerErrors)
        Settings.enableLoggingBehavior(.graphAPIDebugInfo)
        Settings.enableLoggingBehavior(.accessTokens)
        // Settings
        Settings.isAutoLogAppEventsEnabled = true
        Settings.setAdvertiserTrackingEnabled(true)
        Settings.isAdvertiserIDCollectionEnabled = true
```

Facebook related config in my plist file:
```
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>fb[FACEBOOK_APP_ID]</string>
      </array>
    </dict>
  </array>
  <key>FacebookAdvertiserIDCollectionEnabled</key>
  <true/>
  <key>FacebookAppID</key>
  <string>[FACEBOOK_APP_ID]</string>
  <key>FacebookAutoLogAppEventsEnabled</key>
  <true/>
  <key>FacebookClientToken</key>
  <string>[FACEBOOK_CLIENT_TOKEN]</string>
  <key>FacebookDisplayName</key>
  <string>[FACEBOOK_DISPLAY_NAME]</string>
  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>fbapi</string>
    <string>fb-messenger-api</string>
    <string>fbauth2</string>
    <string>fbshareextension</string>
  </array>
  <key>NSUserTrackingUsageDescription</key>
  <string>Purpose text string here.</string>
```

Sample event example:
```swift
    func emitTestEvent(){
        let ev = "myTestEvent”
        let eventName: AppEvents.Name = AppEvents.Name(rawValue: ev)
        AppEvents.logEvent(eventName)
    }
```

You should also double-check your app’s IOS platform configuration. Especially, if your **bundle ID** matches the one in your XCode project. 

Then in the advanced settings, check **Advertising Accounts**, it should be explained in these [docs](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#step-2--link-your-ad-account). All of my events started firing after I updated my **Ad Account ID** and **Business Manager ID**.

**Test events**
<img width="1015" alt="test events" src="https://user-images.githubusercontent.com/26744931/126938586-e0eae3cd-c7bf-40a2-9fdc-ab6453823ae7.png">

**Overview**
<img width="1011" alt="overview tab" src="https://user-images.githubusercontent.com/26744931/126938633-bd730452-8368-4a9d-94ad-0f5ad3bd6cd7.png">

**Comment by SonChanthem** [comment]
@guerri-17 , @grashupfer99 , Hi

May I know do you login with Facebook and with your device? and did you enable permission for tracking on Facebook App?

Thanks.

**Comment by SonChanthem** [comment]
@KylinChang Hi, 

You've closed this issue because of comments mentioned some tip to enable Tracking permission from Facebook app. 
As my opinion I don't think it correctly at all. Why SDK need enable permission on Facebook to success record event from app? and one more thing we can't force user to enable that permission. 
May you help to more detail about this case of Closed this issue?

So if FB SDK can improve this part, it is our best appropriate.
 

Thanks.

**Comment by grashupfer99** [comment]
> @guerri-17 , @grashupfer99 , Hi
> 
> May I know do you login with Facebook and with your device? and did you enable permission for tracking on Facebook App?
> 
> Thanks.

Yes, I had a facebook app running in a background and enabled a permission for tracking like @julien-tamade did with `requestTracking` [here](https://github.com/facebook/facebook-ios-sdk/issues/1667#issuecomment-883930312).


I don't think it's an issue with the SDK itself, the [docs](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios) could be more informative. Perhaps, we should put our efforts toward creating a sample boilerplate project for this issue #1574

@SonChanthem
I previously got stuck on getting ` code = 200;` from a response body, the response was coming fine but events wouldn't show in the event manager. Try going over the second step, it helped me.

**Comment by SonChanthem** [comment]
> #1574

@grashupfer99 Hi,

So could you help to confirm on your project is your event record correctly? in case we go to Device Setting -> Facebook -> Allow Tracking turn off
![IMG_6604](https://user-images.githubusercontent.com/19567034/126972409-34621340-bcfd-4167-b393-aab80b4c3a3b.PNG)

**Comment by grashupfer99** [comment]
> > #1574
> 
> @grashupfer99 Hi,
> 
> So could you help to confirm on your project is your event record correctly? in case we go to Device Setting -> Facebook -> Allow Tracking turn off
> ![IMG_6604](https://user-images.githubusercontent.com/19567034/126972409-34621340-bcfd-4167-b393-aab80b4c3a3b.PNG)

I've updated my [configuration](https://github.com/facebook/facebook-ios-sdk/issues/1667#issuecomment-886397509) for clarity.

@SonChanthem, You should **switch on** Allow Tracking setting on both apps.

**Comment by SonChanthem** [comment]
> > > #1574
> > 
> > 
> > @grashupfer99 Hi,
> > So could you help to confirm on your project is your event record correctly? in case we go to Device Setting -> Facebook -> Allow Tracking turn off
> > ![IMG_6604](https://user-images.githubusercontent.com/19567034/126972409-34621340-bcfd-4167-b393-aab80b4c3a3b.PNG)
> 
> I've updated my [configuration](https://github.com/facebook/facebook-ios-sdk/issues/1667#issuecomment-886397509) for clarity.
> 
> @SonChanthem, You should **switch on** Allow Tracking setting on both apps.

@grashupfer99, Yes, I do. Unless Facebook **switch on** to Allow Tracking setting can display event in Events Manager correctly. I'm so wonder why SDK required that option from Facebook App? As we are separated app and our app also use FB SDK. If it's like that we are mostly failed to get event tracking due to user rarely to allow tracking on Facebook App.

Anyway thank you @grashupfer99 for your clarify.

**Comment by guerri-17** [comment]
@grashupfer99, @SonChanthem - this may muddy our understanding of Facebook SDK so far but I have not seen an ATT prompt within Facebook app so on my device -> Settings -> Facebook, I have no entry for "Allow Tracking" at all.  Yet as long as Facebook is in background, I see my events in the Overview tab for my prod app but never in Test Events tab.

I have a separate test app but it has no "Authorized Ad Account IDs", is that why I see no Events at all from it?

It would be bad to use Facebook SDK which requires "Allow Tracking" for both a non-Facebook app and an active Facebook app for logEvent to work.  This requires too much instruction or expectation from user.  Thank you both.

**Comment by nickangtc** [comment]
https://www.adexchanger.com/mobile/facebook-undercounted-skadnetwork-conversions-for-iphone-12-users-since-february/

**Comment by ironmanalex** [comment]
Hi great community, 

does anyone know how to solve this? We would be willing to pay for a consultation call, we are struggling so much with this :( 

thank you. 

You can email us here:
isaiahturnermyers@gmail.com

Thanks in advance to ANYONE :)

**Comment by ZArez22** [comment]
It’s really a problem of Facebook SDK. We also have problem to see mobile_installs?Cause Facebook SDK send Advetisiement identifier 000000-0000





S pozdravem

Milan Zářecký - umělecký fotograf
+420 777 88 99 27
http://www.zarecky.com <http://www.zarecky.com/>
"Myslete na přírodu. Skutečně potřebujete vytisknout tento e-mail?"
"Before printing, think about enviroment."
**********************************************************************

**Comment by af-obodovskyi** [comment]
> Tip for anybody not getting test events in events manager even while being logged in to facebook app: Make sure you have tracking enabled on the Facebook app too. My tracking for facebook app was turned off but once i turned it on i started to get the events.

This one really helped, I have spent whole 2 days to fixing this up! My credits!

**Comment by matte5031** [comment]
Hello, the only question I have is. Will I be able to track app purchases so that my facebook ads can optimize for purchase without having to ask and get consent from the user to "track them"? If yes, how can that even be good or reliable since only 20% accept to be tracked. Hence, 80% of the purchases will be missed and fb won't be able to optimize corretly and ROAS will not be correct in ads manager, right???

**Comment by jacobsapps** [comment]
We've been trying to get this working for 2 months before I found this thread. 

Based on reading here, and experimenting myself, I was only able to detect events when:
1. My phone enabled requests for advertiser tracking 
2. I was logged into the FB app with advertiser tracking enabled 
3. In my app, `ATTrackingManager.requestTrackingAuthorization` is called and `status == .authorized`
4. And subsequently setting `Settings.shared.isAdvertiserTrackingEnabled = true`

What I need to know is:
1. **Is there a way to track app installs *without* asking for tracking permission?** I have a hunch this will cripple our activation rate if we ask our users to track them. Just tracking installs would be a fair compromise if it means we don't need to request permissions. This has to be possible, because all our other advertisers (Reddit, Google) worked without requesting permission through SKAdNetwork. 
2. Is there a way to get any other event data without requesting tracking permissions? We don't understand why Mixpanel or Firebase allows us to send simple analytics events but Facebook needs us to track our users. 

Thanks in advance to anyone who can respond.

**Comment by appcornerit** [comment]
Hi, not sure it's help, I start to see the events after the completion of connect the data origin process sending an email to me. It's enough weird?

**Comment by h4z4rd0uSm1ke** [comment]
That option is not showing up in Facebook settings anymore... Any clue?

**Comment by h4z4rd0uSm1ke** [comment]
For someone facing this issue of events not reaching, my solution was to go here: https://www.facebook.com/ads/manager/accounts/ and make sure your app advertiser ID is set here:
![facebook-ad-id](https://user-images.githubusercontent.com/10924421/155302648-f5547bd3-d203-4141-8855-a9bbdfde12fa.png)

**Comment by h4z4rd0uSm1ke** [comment]
I've also noticed custom events showing up  in Overview section with filter "All Events" or "Custom Events" but not in the real time section.

**Comment by ggirotto** [comment]
Why is so difficult to Facebook provide a SIMPLE guide about the impacts and actions needed with new Apple ATT? When ATT request is necessary? What events are impacted if not requesting ATT?

**Comment by jiafeiinfinit** [comment]
Hi
  Did anyone resolve this issue?  we get the same issue here. the app event does not show on the dashboard with the error message - Not receiving Events via Facebook iOS SDK

FBSDK version : 12.2.1
IOS version: 14.8.1

**Comment by h4z4rd0uSm1ke** [comment]
Just to contribute to this thread.
I can confirm that although events were not showing up in the real time section nor even in the Overview section, once we published our app in the Apple Store, events are now showing up in the Overview section, although there seemed to be a delay of 1-2 days once they all started showing correctly.

**Comment by dreampowder** [comment]
everything is working except 'app install' seems to be 'inactive'. does anyone with the similar results have a solurion?

**Comment by erikmillergalow** [comment]
I'm having trouble parsing through the FB docs and convos around this, can anyone confirm/deny that you can track app installs on iOS without asking for tracking permission?

The only event we want to track is app installs from FB ads, I'm not sure it's worth it if we have to prompt the user for ATT permissions.

**Comment by ggirotto** [comment]
In my case we haven't asked for ATT and the app installs are being tracked in iOS

**Comment by SRReddy411** [comment]
> After thoroughly reading through everyone's suggestions and commentaries above, I've come up with the following configuration, and I confirm that events are displayed in **Test Events** and later in **Overview**.
> 
> **AppDelegate.swift**
> 
> ```swift
> func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
>       
>         ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
>         // Logging Behavior 
>         Settings.enableLoggingBehavior(.appEvents)
>         Settings.enableLoggingBehavior(.networkRequests)
>         Settings.enableLoggingBehavior(.developerErrors)
>         Settings.enableLoggingBehavior(.graphAPIDebugInfo)
>         Settings.enableLoggingBehavior(.accessTokens)
>         // Settings
>         Settings.isAutoLogAppEventsEnabled = true
>         Settings.setAdvertiserTrackingEnabled(true)
>         Settings.isAdvertiserIDCollectionEnabled = true
>         
>         requestTracking()
>         
>         return true
>     }
>  
> func requestTracking(){
>             if #available(iOS 14, *) {
>                 ATTrackingManager.requestTrackingAuthorization(completionHandler: { (status) in
>                     switch status{
>                     case .authorized:
>                         Settings.setAdvertiserTrackingEnabled(true)
>                         break
>                     case .denied:
>                         Settings.setAdvertiserTrackingEnabled(false)
>                     default:
>                         break
>                     }
>                 })
>             }
>     }
> ```
> 
> Facebook related config in my plist file:
> 
> ```
>   <key>CFBundleURLTypes</key>
>   <array>
>     <dict>
>       <key>CFBundleURLSchemes</key>
>       <array>
>         <string>fb[FACEBOOK_APP_ID]</string>
>       </array>
>     </dict>
>   </array>
>   <key>FacebookAdvertiserIDCollectionEnabled</key>
>   <true/>
>   <key>FacebookAppID</key>
>   <string>[FACEBOOK_APP_ID]</string>
>   <key>FacebookAutoLogAppEventsEnabled</key>
>   <true/>
>   <key>FacebookClientToken</key>
>   <string>[FACEBOOK_CLIENT_TOKEN]</string>
>   <key>FacebookDisplayName</key>
>   <string>[FACEBOOK_DISPLAY_NAME]</string>
>   <key>LSApplicationQueriesSchemes</key>
>   <array>
>     <string>fbapi</string>
>     <string>fb-messenger-api</string>
>     <string>fbauth2</string>
>     <string>fbshareextension</string>
>   </array>
>   <key>NSUserTrackingUsageDescription</key>
>   <string>Purpose text string here.</string>
> ```
> 
> Sample event example:
> 
> ```swift
>     func emitTestEvent(){
>         let ev = "myTestEvent”
>         let eventName: AppEvents.Name = AppEvents.Name(rawValue: ev)
>         AppEvents.logEvent(eventName)
>     }
> ```
> 
> I've tested on a real iPhone device (Software Version: 14.5.1). I ran a facebook app in background along with my app. Also backing up @julien-tamade's [commentary](https://github.com/facebook/facebook-ios-sdk/issues/1667#issuecomment-884360236) that tracking should be enabled on both apps (facebook app and your app on which you're testing events). You can enable it manually from app's settings **> Allow Tracking > On**
> 
> You should double-check your app’s iOS platform configuration. Especially, if your facebook app's bundle ID matches your app.
> 
> Then in the advanced settings, check **Advertising Accounts**, it should be explained in these [docs](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#step-2--link-your-ad-account). All of my events started firing after I updated my **Ad Account ID** and **Business Manager ID**.
> 
> **Test events** <img alt="test events" width="1015" src="https://user-images.githubusercontent.com/26744931/126938586-e0eae3cd-c7bf-40a2-9fdc-ab6453823ae7.png">
> 
> **Overview** <img alt="overview tab" width="1011" src="https://user-images.githubusercontent.com/26744931/126938633-bd730452-8368-4a9d-94ad-0f5ad3bd6cd7.png">

hi same thing i am follow but in ios 14.8.1 version i can't see my events

**Comment by i8ramin** [comment]
> I'm having trouble parsing through the FB docs and convos around this, can anyone confirm/deny that you can track app installs on iOS without asking for tracking permission?
> 
> 
> 
> The only event we want to track is app installs from FB ads, I'm not sure it's worth it if we have to prompt the user for ATT permissions.

exactly this. this is all we want to track as well. do we need to ask user for ATT permissions? if so, then auto tracking app lifecycle events is basically useless, since they fire before user has had a chance to respond to ATT prompt

**Comment by beaneymidnite** [comment]
Experiencing something similar. To date I have still not managed to use the "Test Events" tab successfully, despite trying everything on this thread.

Additionally, I cannot use the "Configure App Events for iOS 14.5 and later Ad Optimizations" in the dashboard. I send the notification which arrives, tap it, which opens my app, and I wait. Nothing happens in the dashboard. It hangs and then gives a "Can't connect" error, with some vague "turn it off and on again"-type instructions.

This needs attention IMO.

**Comment by erikmillergalow** [comment]
I was eventually able to get app install events to fire without requesting ATT but it took a lot of trial/error, slogging through multiple versions of Meta docs, and github issues.

This might not be 100% comprehensive but I had to add this to AppDelegate.m in didFinishLaunchingWithOptions:

` 
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBAEMKit/FBAEMKit.h>

...

[[FBSDKApplicationDelegate sharedInstance] application:application
                         didFinishLaunchingWithOptions:launchOptions];
  [FBSDKApplicationDelegate.sharedInstance initializeSDK];
  [FBSDKSettings.sharedSettings setAdvertiserTrackingEnabled:YES];
  [FBSDKSettings.sharedSettings setAutoLogAppEventsEnabled:YES];`

and this to openUrl:

`  [FBAEMReporter configureWithNetworker:nil appID:@YourFBAppID];
  [FBAEMReporter enable];
  [FBAEMReporter handleURL:url];
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }`

This to Info.plist:

`	<key>FacebookAppID</key>
	<string>YourFBAppID</string>
	<key>FacebookClientToken</key>
	<string><YourClientToken></string>
	<key>FacebookDisplayName</key>
	<string>YourFBAppName</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
	</array>

	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fbYourFBAppID</string>
			</array>
		</dict>
                 ....
	</array>
	<key>CFBundleVersion</key>
`

The URL scheme is added in addition to any others you already have there. Something that tripped me up initially was leaving out the 'fb' at the beginning of the app ID in the URL scheme.

As others have mentioned, be sure to be signed in to the FB app (using the same account that you use for FB Business) and have it open in the background while first trying to view test events in the event manager.

**Comment by beaneymidnite** [comment]
Ah okay, you're just doing SKAdNetwork. I'm also interested in Aggregated Event Measurement, which relies on other events being sent via the Facebook SDK.

Interestingly, your tips did get me one step further in the chain - I can now "set up" AEM in the dashboard under the "Configure App Events for iOS 14.5 and later Ad Optimizations" section, but it's now telling me there's no events in the last 90 days, and to check the overview tab (which has events coming in from the last 2 days, let alone 90!).

**Comment by ahtokca** [comment]
it is unbelievably hard to make events appear at Events Manager. Spent 2 days with no success. I see events being sent via adb logcat and iPhone console however Event Manager/Test Events shows nothing.
All of that gives me no confidence that FB treats the app data seriously :(

**Comment by imbimp** [comment]
Keeping this thread alive as spent months trying to get this to work. Tried everything above, still getting no events despite seeing them come out of the app in network requests.

**Comment by DonTharaka** [comment]
Facebook [documentation](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios) on app events is very vague. It does not contain any information about ATTrackingManager which is necessary to track events.  First follow all steps in the documentation. Below are the steps I have taken to successfully connect app events (iOS 15):

1. Info.Plist
![Screen Shot 2022-08-11 at 10 44 47 am](https://user-images.githubusercontent.com/6435171/184047970-0e27f638-2a67-4f43-ae28-67a73228cde8.png)

2. SceneDelegate

![Screen Shot 2022-08-11 at 10 50 43 am](https://user-images.githubusercontent.com/6435171/184048081-e2c32cb9-21ee-4327-b481-e0e5ad152428.png)

![Screen Shot 2022-08-11 at 11 05 33 am](https://user-images.githubusercontent.com/6435171/184048154-c349c273-e012-4e6c-8b56-592561d23905.png)

![Screen Shot 2022-08-11 at 10 48 40 am](https://user-images.githubusercontent.com/6435171/184048101-4845b81c-7dc0-4a9e-91ad-6e47277134eb.png)

This will bring up the following pop up:

![Screen Shot 2022-08-11 at 10 58 05 am](https://user-images.githubusercontent.com/6435171/184048201-c05fbeb0-de13-48f9-ab15-e0b501cf83c5.png)


3. In your viewcontroller:

![Screen Shot 2022-08-11 at 10 52 39 am](https://user-images.githubusercontent.com/6435171/184048216-467ac32f-56dc-4821-8ee4-8b63e576dfbc.png)

**Comment by tharwi** [comment]
Hi @DonTharaka, Don't you want to set up like this in the Info.plist,

```
<key>FacebookAutoLogAppEventsEnabled</key>
<false/>
<key>FacebookAdvertiserIDCollectionEnabled</key>
<false/>
<key>NSUserTrackingUsageDescription</key>
<string>For app events</string>
```

Then after getting the user consent you have to mark them as true

**Comment by camboYY** [comment]
i have it worked only on simulator

**Comment by pballada** [comment]
In my case everything worked once I entered the bundle identifier in the Settings > Basic > iOS.
Not sure what is wrong with that field but the bundle id was not saving.

**Comment by sampath1994** [comment]
Any update on this?

**Comment by artur-zaremba** [comment]
The same issue there. It would be great to see helpful initialisation warnings in console instead of suggestions about logger flags. At first I want to init SDK properly 🥹

**Comment by calsmith** [comment]
Any update on this?

**Comment by rlomeli158** [comment]
Reopening. Still not fixed.

**Comment by poncemari** [comment]
Still can’t logging

Mp

**Comment by Olegmaksimmenko** [comment]
Reopening. Still not fixed.

**Comment by 811414114** [comment]
**_[![image](https://github.com/facebook/facebook-ios-sdk/assets/144417527/4aa67a00-8318-47ef-b096-a09d96cc481e)](https://x.com/youtube/status/1791524084351660123?s=46)_**@hannan07rohan
> #- [ ] ~~````

````~~

**Comment by sagarthecoder** [comment]
The event is fired in the Analytics board, but I couldn't find it in the Test Event Section. I have tried all the solutions from this discussion, but it's still not working.
SDK version: 18.0.0
iOS version: 18.3.2

**Comment by danyalutsevich** [comment]
why it was closed? is there a solution for that?
still cant see events in the test tab
