### ISSUE TITLE
tvOS via SPM issues (no FBAEMKit library, no FBSDKTVOSKit)

### ISSUE THREAD

**Issue by drdaz** [facebook/facebook-ios-sdk#1936]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.1

### Facebook iOS SDK version

12.1.0

### Dependency Manager

SPM

### SDK Framework

Core

### Goals

I help maintain the [Parse iOS SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX). I'm looking to use SPM for our dependencies on the FB SDK. These are FBSDKCoreKit, FBDSKCoreKit_Basics, FBSDKTVOSKit.

### Expected results

Including libs via SPM gives me access to the corresponding library's functionality within my app, across all platforms.

For example, including the FacebookCore dependency should get me access to the FBSDKCoreKit features in my project.

### Actual results

All libraries fail to build on tvOS. There seems to be a dependency on FBAEMKit, and FBAEMKit doesn't seem to build for tvOS via SPM.

I don't see any equivalent for FBSDKTVOSKit to add via SPM either.

<img width="696" alt="Screenshot 2021-11-09 at 21 06 49" src="https://user-images.githubusercontent.com/845731/140996851-4908f444-e8d2-4907-ba95-fec9df989316.png">

<img width="411" alt="Screenshot 2021-11-09 at 21 08 02" src="https://user-images.githubusercontent.com/845731/140997019-d9ff0007-441d-438e-924a-04830cbdd138.png">

### Steps to reproduce

1. Make a new tvOS project
2. Add the 12.1.0 release as an SPM dependency
3. Add FacebookCore as a project dependency
4. Build the project
5.

**Comment by jawwad** [comment]
Hi @drdaz - Sorry about the late response on this, and we really appreciate the detailed writeup and screenshots on this. @joesus has updated FBAEMKit so that it can be compiled with tvOS. We just released v12.2.1. Can you see if this fixes the issue for you?

**Comment by drdaz** [comment]
Hey @jawwad thanks for that. This release seems to add the FBAEMKit as you describe, but I still don't see any way of adding FBSDKTVOSKit via SPM.

**Comment by jsivanes** [comment]
Hello I have the same issue about FKSDKTVOSKIT, can't found it as module, I used the v12.3.1 on Xcode 13.2.1.
Any solution plz?

**Comment by samodom** [comment]
@jsivanes We are publishing TVOSKit in the v13 release via SPM.  After the release (coming very shortly), please give it a shot. If you run into problems at that point, please open another issue specifically referring to that framework's availability.
