### ISSUE TITLE
Improper Swizzling of `application:openURL:options:`

### ISSUE THREAD

**Issue by waltflanagan** [facebook/facebook-ios-sdk#2205]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

14.3

### Facebook iOS SDK version

16.1.0

### Dependency Manager

SPM

### SDK Framework

Core

### Goals

After updating to SDK 16.* we found that `application:openURL:options:` was always returning `NO`/`false` when called.  This is due to swizzling implemented [here](https://github.com/facebook/facebook-ios-sdk/blob/main/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/AEM/FBSDKAEMManager.m#L79). The return value is not passed through this implementation.

We would like to have callers of `application:openURL:options:` receive the correct return value of the method.

### Expected results

If the implementation of `application:openURL:options:` returns `YES` then the callers of the method should receive `YES`

### Actual results

Callers of `application:openURL:options:` always receive `NO`.

### Steps to reproduce

Implement a `UIApplicationDelegate` class and hard core `application:openURL:options:` to return `YES`/`true`.  

Link against `FBAEMKit` and enable it such that it swizzles `application:openURL:options:`

**Comment by squarefrog** [comment]
We're experiencing this issue too - it has broken our deep link implementation, so we're going to have to downgrade.

**Comment by shomin1983** [comment]
We're experiencing the same issue

**Comment by dodatw** [comment]
Same Here!

**Comment by olejnjak** [comment]
It is the same story with `application(_:continue:restorationHandler:) -> Bool` and Facebook SDK 16.3.1

**Comment by olejnjak** [comment]
Here is minimal example for my case [FBSample.zip](https://github.com/facebook/facebook-ios-sdk/files/13929932/FBSample.zip)

**Comment by Cedrick84** [comment]
This issue still exists in 17.0.2
Attached is the AppDelegate illustrating the issue
[AppDelegate.swift.zip](https://github.com/user-attachments/files/16487002/AppDelegate.swift.zip)

**Comment by alex-taffe** [comment]
Same issue here

**Comment by jscalo** [comment]
Same issue here. Can we get the priority raised? I would think this impacts the Xcode 16 deployment of almost every FB-linked app.

**Comment by ptsochantaris** [comment]
One workaround is to pass the `openURL` `OpenURLAction` value from the UI (if you're using SwiftUI) down to your URL handler and use that to open a URL. That does not go through the UIKit route so the FB hack doesn't break it.

For example:
```
    @Environment(\.openURL) private var openURL

    static func openURL(_ url: URL, via action: OpenURLAction) async -> Bool {
        let accepted = await withCheckedContinuation { continuation in
            action(url) {
                continuation.resume(returning: $0)
            }
        }

        if accepted {
            print("Opening external URL: \(url)")
        } else {
            print("Warning: Failed to open external URL: \(url)")
        }
        return accepted
    }
```

I hope this is of help to anyone struggling with the same issue, and hope that FB creates a fix for this soon.

**Comment by RobertDresler** [comment]
How can this be opened since "May 8, 2023" and not be solved? It breaks every open URL call in the app!

**Comment by RobertDresler** [comment]
It seems to be solved in the newest version [17.3.0](https://github.com/facebook/facebook-ios-sdk/releases/tag/v17.3.0).

**Comment by jscalo** [comment]
Confirmed issue is fixed in 17.3.0.

**Comment by vlad-roid** [comment]
While fixed and working in 17.3.0 and 17.4.0, unfortunately SDK 17.x is not safe for production use, see https://github.com/facebook/facebook-ios-sdk/issues/2387.
17.x introduces the concept of limited login which is a major breaking change, tbh a completely silly decision preventing everyone who rejects ATT from using Facebook sign in. For example as per [FAQ](https://developers.facebook.com/docs/facebook-login/limited-login/faq) limited login does not support business permissions. Note that the suggested "classic login" option in fact does not exist - rejecting ATT [triggers hardcoded limited login code](https://github.com/facebook/facebook-ios-sdk/issues/2375#issuecomment-2051743845).

The solution I've used successfully instead (at least until Graph API 16 is deprecated) is using `UIApplication.shared.open(url, options: [:], completionHandler: nil)` instead of `UIApplication.shared.open(url)` as only the latter is affected by this swizzling disaster.

**Comment by ODKPierre** [comment]
@vlad-roid I used 17.4.0 and I still have the issue, it does not look like it's solved in recent version either.

**Comment by GuiAguirres** [comment]
I'm still facing this very same issue here with `FBSDKFeatureAppAemAutoSetUpProxy` being false, even on version 18.0.1/18.0.2... I don't know what to do anymore, my `application(:userActivity:restorationHandler:)` function is returning false to caller even though I return true on it.

**Comment by Zhiyi-Zhang** [comment]
This issue has been fixed. The fix has landed internally and will be available in an upcoming release. Closing.
