### ISSUE TITLE
App is live but only approved testers can login (using limited login on 17.0.0)

### ISSUE THREAD

**Issue by rgg-egunnery** [facebook/facebook-ios-sdk#2387]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

15.3

### Facebook iOS SDK version

17.0.0

### Dependency Manager

SPM

### SDK Framework

Login

### Goals

Login for all users

### Expected results

I expect both test users and regular users to be handled correctly when the app is live.

### Actual results

I keep getting a cancellation returned when trying to use the new login method for limited login, only for non test users.

### Code samples & details

```swift
self?.loginManager.logIn(configuration: configuration) { result in
                switch result {
                case .cancelled:
                    continuation.resume(throwing: Cancelation()) <--- hits every time I try login from a non tester account
                }
            }
```

**Comment by fgeracitano** [comment]
Any news on this one?

**Comment by giorgia** [comment]
same

**Comment by tommy6457** [comment]
same here

**Comment by kishore-chandru-poshmark** [comment]
same here

**Comment by rgg-clineu** [comment]
same here

**Comment by hollyShine** [comment]
same,and I had to drop the version to 16.3.1

**Comment by bluerainxty** [comment]
any updates?

**Comment by alexEulerity** [comment]
> same,and I had to drop the version to 16.3.1

Don't we need version 17.0.0 to conform to Apple's Privacy Policy, since version 17.0.0 has the Policy Privacy File?

**Comment by chorobochrontochor** [comment]
+1

**Comment by rgg-egunnery** [comment]
Just confirming that this is also the case on 17.0.1

**Comment by gupta515** [comment]
> > same,and I had to drop the version to 16.3.1
> 
> Don't we need version 17.0.0 to conform to Apple's Privacy Policy, since version 17.0.0 has the Policy Privacy File?

+1

**Comment by gupta515** [comment]
> same,and I had to drop the version to 16.3.1

Did your build pass through Apple's Privacy Policy check?

**Comment by SamuelZhaoY** [comment]
same!, and 

> Just confirming that this is also the case on 17.0.1

yes, same on 17.0.1

**Comment by SamuelZhaoY** [comment]
Actually it is a very terrible upgrade experience since we are informed only by early April that we need to upgrade to FB 17.0.0/17.0.1 in order to comply with apple's privacy manifest requirement which will start from May

**Comment by SamuelZhaoY** [comment]
Our company have more than 10 FB Application, after migrating to iOS FBSDK 17.0.0.
We found that when using one of the Facebook AppID and ClientToken, the following method always return result with `isCancelled = true`. 

```objc
- (void)logInFromViewController:(UIViewController * _Nullable)viewController 
                                configuration:(FBSDKLoginConfiguration * _Nullable)configuration 
                                    completion:(FBSDKLoginManagerLoginResultBlock _Nonnull)completion;
```

What makes our team confused is that: 

- Previously when using the 16.2.1 version of the SDK, the FB App configuration is working fine. Now the issue happens for both 17.0.0 and 17.0.1
- **The rest of the FB App configurations (around 10) is working fine, yet the single FB App has such issue** 🤔️
- For the same xcode workspace, as soon as we change the FacebookClientToken/FacebookAppID and the URL in the app's **info.plist** , things can work as expected. 

Not sure it is a bug in the Facebook Login SDK or any potential misconfiguration on the Facebook Developer console

```swift
FBSDKLoginManager *login = [[FBSDKLoginManager alloc] init];
    FBSDKLoginConfiguration *configuration = [[FBSDKLoginConfiguration alloc]
                                              initWithPermissions:@[@"public_profile", @"email"]
                                              tracking:FBSDKLoginTrackingLimited];
    [login logInFromViewController:[UITool getCurrentVC]
                     configuration:configuration
                        completion:^(FBSDKLoginManagerLoginResult * _Nullable result, NSError * _Nullable error) {
        if (error) {
            // error
        } else if (result.isCancelled) {
            //
            // this is the code always goes to under one
            // of the specific fb app configuration
            // 
        } else {
            // success, which should be expected
        }
        callback(responseDic);
    }];
```

**Comment by hollyShine** [comment]
> > same,and I had to drop the version to 16.3.1
> 
> Don't we need version 17.0.0 to conform to Apple's Privacy Policy, since version 17.0.0 has the Policy Privacy File?
build passed

**Comment by hollyShine** [comment]
> > same,and I had to drop the version to 16.3.1
> 
> Did your build pass through Apple's Privacy Policy check?

passed

**Comment by hollyShine** [comment]
> > same,and I had to drop the version to 16.3.1
> 
> Don't we need version 17.0.0 to conform to Apple's Privacy Policy, since version 17.0.0 has the Policy Privacy File?

16.3.1 build passed through Apple's check for me

**Comment by rgg-egunnery** [comment]
We had a call with Facebook last Thursday to discuss this and I've sent them the logs I collected for success vs failure for test and public accounts. They had no solution to offer on the call for this, but I will update this thread if I hear anything further.

**Comment by fgeracitano** [comment]
their latest suggestion is: "you need to submit for review" 


- the app was working for 16.3.1 for public users
- the app is in published state already
- the is no submit for review button if you ask only basic email / public profile
- they state "Most permissions must be approved"

if that is the real problem there must be a bug on their review app flow

**Comment by BunLV** [comment]
I tested with many fb app and i see: with fb app go live, if fb sdk ios version on "App Settings/Advanced/Check your SDK version": 
- fb sdk version 15.x or later => its worked 
- fb sdk version under 15.x => always return cancel

I hope it can help fb developer team detect this issue.

**Comment by mrhodangduy** [comment]
> I tested with many fb app and i see: with fb app go live, if fb sdk ios version on "App Settings/Advanced/Check your SDK version":
> 
> * fb sdk version 15.x or later => its worked
> * fb sdk version under 15.x => always return cancel
> 
> I hope it can help fb developer team detect this issue.

<img width="1068" alt="Screenshot 2024-05-13 at 13 50 46" src="https://github.com/facebook/facebook-ios-sdk/assets/29606594/d5445745-74c2-438d-9f16-34e4634f9f0d">

In my FB App Setting, it display like that. What's wrong?

**Comment by fgeracitano** [comment]
> > I tested with many fb app and i see: with fb app go live, if fb sdk ios version on "App Settings/Advanced/Check your SDK version":
> > 
> > * fb sdk version 15.x or later => its worked
> > * fb sdk version under 15.x => always return cancel
> > 
> > I hope it can help fb developer team detect this issue.
> 
> <img alt="Screenshot 2024-05-13 at 13 50 46" width="1068" src="https://private-user-images.githubusercontent.com/29606594/329951251-d5445745-74c2-438d-9f16-34e4634f9f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY3NjYsIm5iZiI6MTcxNTU5NjQ2NiwicGF0aCI6Ii8yOTYwNjU5NC8zMjk5NTEyNTEtZDU0NDU3NDUtNzRjMi00MzhkLTlmMTYtMzRlNDYzNGY5ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NjI2MDY5NTE4YTVmOTQ1ZjUyNTlkZDI3ZDliOTdmNjZkZjNkMjA1YjkxZGUzNWJhMDBmMDQ5MGYzN2FjZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NBvX13XV8gYRCyjJLe2s4SXl5VoqX5Tzljw_VQ590L4">
> In my FB App Setting, it display like that. What's wrong?

It's a know problem on their side, they don't keep track of the latest release,  and that piece of UI tands to bring even more confusion  🤦 

<img width="277" alt="Screenshot 2024-05-13 at 12 35 27 PM" src="https://github.com/facebook/facebook-ios-sdk/assets/129771338/6df0375e-9876-4c51-b8c4-a07514af3fbb">

**Comment by marcin-piela-800** [comment]
We have iOS v15.0.0 and it's not working

**Comment by xsgoing** [comment]
same in V17.0.1

**Comment by kiyakkoray** [comment]
same happens to us in unity sdk as well

**Comment by BunLV** [comment]
> We have iOS v15.0.0 and it's not working

I tested and it's working on fb sdk v15.1.0 (>10 fb app id)

**Comment by BunLV** [comment]
> > > I tested with many fb app and i see: with fb app go live, if fb sdk ios version on "App Settings/Advanced/Check your SDK version":
> > > 
> > > * fb sdk version 15.x or later => its worked
> > > * fb sdk version under 15.x => always return cancel
> > > 
> > > I hope it can help fb developer team detect this issue.
> > 
> > 
> > <img alt="Screenshot 2024-05-13 at 13 50 46" width="1068" src="https://private-user-images.githubusercontent.com/29606594/329951251-d5445745-74c2-438d-9f16-34e4634f9f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY3NjYsIm5iZiI6MTcxNTU5NjQ2NiwicGF0aCI6Ii8yOTYwNjU5NC8zMjk5NTEyNTEtZDU0NDU3NDUtNzRjMi00MzhkLTlmMTYtMzRlNDYzNGY5ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NjI2MDY5NTE4YTVmOTQ1ZjUyNTlkZDI3ZDliOTdmNjZkZjNkMjA1YjkxZGUzNWJhMDBmMDQ5MGYzN2FjZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NBvX13XV8gYRCyjJLe2s4SXl5VoqX5Tzljw_VQ590L4">
> > In my FB App Setting, it display like that. What's wrong?
> 
> It's a know problem on their side, they don't keep track of the latest release, and that piece of UI tands to bring even more confusion 🤦
> 
> <img alt="Screenshot 2024-05-13 at 12 35 27 PM" width="277" src="https://private-user-images.githubusercontent.com/129771338/330022096-6df0375e-9876-4c51-b8c4-a07514af3fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDE3MzgsIm5iZiI6MTcxNTc0MTQzOCwicGF0aCI6Ii8xMjk3NzEzMzgvMzMwMDIyMDk2LTZkZjAzNzVlLTk4NzYtNGM1MS1iOGM0LWEwNzUxNGFmM2ZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwMjUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRkY2YyM2E1OWNiZWZkYmJjOGJiYjhmNWNmYzYzNDA1NTVkMGVhOWYyZmU4ZDYxOGMwYmUyNWU2MjgwMWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DilmWiQReERWiMHmJu-SAQI4f6wo3NNntpp6_E1zKo4">

I submited my app with a fb app id not worked, i'm waitting for fb console update SDK version to fb sdk v17.0.1.
I hope it will work for this fb app id. Anybody try this case?

**Comment by xsgoing** [comment]
I have two app，they have same sdk version
![image](https://github.com/facebook/facebook-ios-sdk/assets/13741258/bb9463fb-4428-401a-a573-3841ee22bb58)
but only one worked ，one not。 @BunLV

**Comment by rgg-egunnery** [comment]
Hi all. We received an email from Facebook a few minutes ago saying that this issue has been fixed. Without any changes on our end, it seems that we can now login with public accounts. You might want to give yours a try. I am curious if this needs to be fixed on an account basis or if this was a general bug fix in the backend.

**Comment by kiyakkoray** [comment]
> Hi all. We received an email from Facebook a few minutes ago saying that this issue has been fixed. Without any changes on our end, it seems that we can now login with public accounts. You might want to give yours a try. I am curious if this needs to be fixed on an account basis or if this was a general bug fix in the backend.

We just have tried but it's still not working.

**Comment by BunLV** [comment]
> Hi all. We received an email from Facebook a few minutes ago saying that this issue has been fixed. Without any changes on our end, it seems that we can now login with public accounts. You might want to give yours a try. I am curious if this needs to be fixed on an account basis or if this was a general bug fix in the backend.

I tested on all our fb app and it's still not working :( (account test & account normal)

**Comment by BunLV** [comment]
Updated: I tested and it's not working only iOS 17.x, below 17.x it worked

**Comment by kiyakkoray** [comment]
> Update: I jumped the gun. We have two apps, the first was working and the second was not. We contacted them again and now the second is working. It appears this needs to be fixed on a per app basis, presumably just some configuration on their end.

Do they at least know that this is a common problem and are they trying to fix it?

**Comment by marcin-piela-800** [comment]
> Update: I jumped the gun. We have two apps, the first was working and the second was not. We contacted them again and now the second is working. It appears this needs to be fixed on a per app basis, presumably just some configuration on their end.

How did you contact them? It's not very straightforward...We have informed them about this problem several times with each app rejection, but it seems like it is a bot, not a human...

**Comment by rgg-egunnery** [comment]
> > Update: I jumped the gun. We have two apps, the first was working and the second was not. We contacted them again and now the second is working. It appears this needs to be fixed on a per app basis, presumably just some configuration on their end.
>
> Do they at least know that this is a common problem and are they trying to fix it?

I have stressed that this is a widespread issue and asked the check out all these raised issues. Given they had to do a separate fix for each of our apps, I think they're likely working on a fix for the SDK as a hole and this was just a stop gap as we were able to contact them. Even if they do believe this is low impact, I am hopeful they don't think it's reasonable to just keep fixing apps one by one. 

> 
> How did you contact them? It's not very straightforward...We have informed them about this problem several times with each app rejection, but it seems like it is a bot, not a human...

We have an account manager for Facebook so one of our product managers was able to reach out.

**Comment by haryelramalho** [comment]
Does anyone know how I can disable limited login? Because I need the access token to make some requests to graph API...

**Comment by daleiLV** [comment]
> I have two app，they have same sdk version ![image](https://private-user-images.githubusercontent.com/13741258/330647163-bb9463fb-4428-401a-a573-3841ee22bb58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzI3NTAsIm5iZiI6MTcxNjQzMjQ1MCwicGF0aCI6Ii8xMzc0MTI1OC8zMzA2NDcxNjMtYmI5NDYzZmItNDQyOC00MDFhLWE1NzMtMzg0MWVlMjJiYjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MTNiOGUwMDgxZDA0N2I4MmExMGFiMDc3OTYwY2FhOWVlMTEyNTcxN2Q0ZWI5ZTIzM2M4MTdkODQyNjg3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uo0BC4j0aOGNnv5TAQ5iq8wdX9zqFM3WX7jbG9dg4ek) but only one worked ，one not。 @BunLV and my sdk version is V17.0.1

您好，该问题解决了吗？如果解决了，怎么解决的呢？

**Comment by xsgoing** [comment]
not yet

**Comment by rgg-egunnery** [comment]
> Does anyone know how I can disable limited login? Because I need the access token to make some requests to graph API...

You can't. You can set the login configuration to .enabled (which it does by default anyway) or to .limited. If set to .enabled, if the user has tracking completely disabled on device it'll still route to .limited. Facebook's documentation goes through how to handle this case vs .enabled, and it does work for test accounts, but the wall was hit for us with public accounts. Facebook had to fix each of our apps on a case by case basis for this, something was done on their end.

**Comment by EvansPie** [comment]
Same in v.17.0.2

**Comment by kaancembertas** [comment]
Same here

**Comment by gupta515** [comment]
> Same in v.17.0.2

Yes, even it is same in the tag 17.0.2, though we are passing the transaction mode as `.enabled` it is still loading `.limited`. It's already been weeks waiting for the stable version from Facebook.

**Comment by kiyakkoray** [comment]
any workaround yet?

**Comment by bluerainxty** [comment]
这么久了，也没人解决

**Comment by chenium** [comment]
I think I'm experiencing something similar and related to this via the Facebook SDK graph api. I'm able to receive an access token through login but using the token to make requests with graph api results in a connectivity error.

```
Task <03A2BA6B-42BB-43E9-BB37-159B2C919240>.<25> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x301e71ad0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: lo0, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <03A2BA6B-42BB-43E9-BB37-159B2C919240>.<25>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <03A2BA6B-42BB-43E9-BB37-159B2C919240>.<25>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://localhost:9090/com.snowplowanalytics.snowplow/tp2, NSErrorFailingURLKey=http://localhost:9090/com.snowplowanalytics.snowplow/tp2, _kCFStreamErrorDomainKey=1}
```
This is not the case with v16.x.x

One thing I found that fixes this is to utilize Apple's app tracking transparency manager to request tracking permission. If the user grants permission, then the graph api requests begin to work. We haven't had the need to make this request because we don't track users across apps and will be inconvenient for us to ask our users for this permission just for Facebook login to work. 

I'm curious for other developers experiencing this issue if requesting app tracking persmission resolves your issue.

**Comment by chenium** [comment]
I think I'm experiencing something similar and related to this via the Facebook SDK graph api. I'm able to receive an access token through login but using the token to make requests with graph api results in a connectivity error.

```
The Internet connection appears to be offline.
```

This is not the case with v16.x.x

One thing I found that fixes this is to utilize Apple's app tracking transparency manager to request tracking permission. If the user grants permission, then the graph api requests begin to work. We haven't had the need to make this request because we don't track users across apps and will be inconvenient for us to ask our users for this permission just for Facebook login to work.

I'm curious for other developers experiencing this issue if requesting app tracking persmission resolves your issue.

**Comment by margarethchan** [comment]
Has anyone other than OP successfully "unlocked" their apps via Meta Account Manager contact?

**Comment by omz1990** [comment]
Really annoying. Reverting to old version brings back this issue: https://github.com/facebook/facebook-ios-sdk/issues/2353
So basically either we downgrade Xcode to 15.2 or break Facebook login. Great!!!

**Comment by StriderHND** [comment]
Hello guys any updates on this?

**Comment by kiyakkoray** [comment]
still no update?

**Comment by aguzmanrebuy** [comment]
I wonder if this is actually the same issue as #2365.
If so, then the solution would be to support the [limited log in](https://developers.facebook.com/docs/facebook-login/limited-login/ios/) ?

**Comment by kiyakkoray** [comment]
> still no update?

any solution?

**Comment by trickeyd** [comment]
I filled this out in regard to this issue - still waiting for a response.

https://go.facebookinc.com/2018-FB4D-platform-review-form.html

**Comment by gupta515** [comment]
Any update?

**Comment by MaxJadav** [comment]
I'm getting the same issue. Is there any update?

**Comment by pw-repo** [comment]
Have anyone make it succesful to login with production real users with SDK v17.0+?

**Comment by pw-repo** [comment]
> Update: I jumped the gun. We have two apps, the first was working and the second was not. We contacted them again and now the second is working. It appears this needs to be fixed on a per app basis, presumably just some configuration on their end.

Does it work now in September 2024 correctly?

I need to upgrade Facebook SDK to 17.1.3 version to use Privacy Manifest files to pass the App Store review.

**Comment by trickeyd** [comment]
No I heard nothing nothing either @pw-repo . Additionally I have tried various other avenues and have had some of the most infuriating conversations with people from Meta.

No one is owning this. We are just having to migrate our users and remove FB login. It is ridiculous.

**Comment by angelolloqui** [comment]
What an annoying issue! I have no idea why the IDFA should prevent users from doing a FB login, but it makes no sense to me!

Probably not the most robust solution (and I need to verify FB's terms of use are not broken), but I have made [this simple drop in replacement](https://gist.github.com/angelolloqui/070a08877c8f3eb01cb1b6f55647f4e4) for the `LoginManager` that uses the `ASWebAuthenticationSession` following the [manual login flow instructions found in their official documentation](https://developers.facebook.com/docs/facebook-login/guides/advanced/manual-flow). 

You can use it like this:

```
 FacebookSignInHelper.login(permissions: permissions, from: self) { result in
            switch result {
            case let .success(result):
                  // use result.accessToken, result.grantedPermissions
            case let .failure(error):
                Log.e("OnboardingAuthViewController", "Facebook login error: \(error.localizedDescription)")
            }
        }
```

**Comment by FanYouXin** [comment]
> same,and I had to drop the version to 16.3.1

16.3.1 now will reject by apple. Unvalued ipa.
